### ISSUE TITLE
offline tokens still do not work

### ISSUE THREAD

**Issue by leto** [singingwolfboy/flask-dance#10]
Recently there were some commits to allow offline tokens to be requested, but the correct URL parameter is not passed to the underlying libraries, so no refresh tokens are returned. The basic snippet asking for offline access is:

``` python
google_blueprint = make_google_blueprint(client_id=CLIENT_ID, client_secret=CLIENT_SECRET,
                    offline=True, # needed to get refresh tokens! flask 0.4.3 needed
                    scope=YOUTUBE_SCOPES,
                    redirect_url="/oauth2callback",
                    login_url="/google",
                    authorized_url="/catch")

app.register_blueprint(google_blueprint)
```
which produces

```
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://accounts.google.com/o/oauth2/token using method POST.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {u'Content-Type': u'application/x-www-form-urlencoded;charset=UTF-8', u'Accept': u'application/json'} and data {u'code': u'foobar', u'client_secret': u'bar', u'grant_type': u'authorization_code', u'client_id': u'foo', u'redirect_uri': u'http://foo.com/catch'}
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'verify': True, 'json': None, 'timeout': None, 'auth': None}.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /o/oauth2/token HTTP/1.1" 200 None
DEBUG:requests_oauthlib.oauth2_session:Prepared fetch token request body grant_type=authorization_code&code=foobar&redirect_uri=http%3A%2F%2Ffoo.com%2Fcatch&client_id=foo&client_secret=bar
DEBUG:requests_oauthlib.oauth2_session:Request to fetch token completed with status 200.
DEBUG:requests_oauthlib.oauth2_session:Request headers were {'Content-Length': '277', 'Accept-Encoding': 'gzip, deflate', 'Accept': u'application/json', 'User-Agent': 'python-requests/2.5.3 CPython/2.7.6 Linux/3.13.0-45-generic', 'Connection': 'keep-alive', 'Content-Type': u'application/x-www-form-urlencoded;charset=UTF-8'}
DEBUG:requests_oauthlib.oauth2_session:Request body was code=foobar&client_secret=foo&grant_type=authorization_code&client_id=xxx
DEBUG:requests_oauthlib.oauth2_session:Response headers were {'alternate-protocol': '443:quic,p=0.5', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'content-disposition': 'attachment; filename="json.txt"; filename*=UTF-8\'\'json.txt', 'transfer-encoding': 'chunked', 'accept-ranges': 'none', 'expires': 'Fri, 01 Jan 1990 00:00:00 GMT', 'vary': 'Accept-Encoding', 'server': 'GSE', 'pragma': 'no-cache', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'date': 'Thu, 26 Mar 2015 22:52:06 GMT', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json; charset=utf-8'} and content {
  "access_token" : "xxx",
    "token_type" : "Bearer",
	  "expires_in" : 3600
	  }.
```

Notice that an oauth token is returned, but it does not have a refresh_token because the offline=True did not propagate.

This is using Flask-Dance 0.4.3 on Python 2.7.6

**Comment by singingwolfboy** [comment]
Hi @leto, thanks for this information. I've looked at [Google's documentation for offline access](https://developers.google.com/accounts/docs/OAuth2WebServer#offline), and it looks like we need to include an `access_type=offline` parameter in the redirect URL when sending the user to Google to grant consent. The debug output you've provided looks like it's from the step in the dance where we exchange the authorization code for the access token. If you check out [the documentation I wrote earlier today about how OAuth works](http://flask-dance.readthedocs.org/en/latest/how-oauth-works.html), the offline parameter gets sent in step 2, and the debug output you've provided is from step 5.

When Flask-Dance redirects you to Google to grant consent, can you examine the URL on the consent page, and see if it contains `access_type=offline`?

**Comment by leto** [comment]
Yes, inspecting the URL of the consent screen does show that it has "access_type%3Doffline" . There seems to be something not completely implemented, though, because I don't get a refresh_token stored in my database table for the oauth tokens.

**Comment by singingwolfboy** [comment]
@leto: you may need to revoke the OAuth token and try again, if you granted consent the first time without offline access enabled. I've also pushed a commit to master that should allow you to specify `reprompt_consent=True`, which should force Google to re-prompt for the user's consent, which might be enough. Can you give that a try?

Please understand that this is an issue on Google's end, not for Flask-Dance. I'm trying to help you figure this out, but it could be the case that Google's docs are just wrong.

**Comment by leto** [comment]
The ```reprompt_consent=True``` finally made refresh_tokens appear, thank you.
