### ISSUE TITLE
Missing required parameter: refresh_token

### ISSUE THREAD

**Issue by blohinn** [singingwolfboy/flask-dance#102]
I have a custom backend. All works fine, but i have problem when token was expired...
What about refresh token? I didnt find anything about this problem...

Custom backend:
```
class MongoBackend(BaseBackend):
    def get(self, blueprint):
        from ..collections import users_collection
        try:
            user = users_collection.find_one({'_id': ObjectId(current_user.id), 'oauth.provider': 'google'})
            return user['oauth']['token']
        except:
            return None

    def set(self, blueprint, token):
        from ..collections import users_collection
        users_collection.update_one({'_id': ObjectId(current_user.id)}, {'$set': {'oauth.token': token}})

    def delete(self, blueprint):
        from ..collections import users_collection
        users_collection.update_one({'_id': ObjectId(current_user.id), 'oauth': {'$set': {'token': ''}}})  # i know that didnt work
        return None
```
User scheme:
```
{
    "_id" : ObjectId("5a3d489ecefa5b3ad0b77b46"),
    "email" : "blablabla@gmail.com",
    "oauth" : {
        "provider" : "google",
        "token" : {
            "access_token" : "bla bla bla",
            "expires_in" : 3420,
            "id_token" : "bla bla bla",
            "token_type" : "Bearer",
            "expires_at" : 1510969326.18578
        }
    }
}
```

When token was expired i see:
**oauthlib.oauth2.rfc6749.errors.InvalidClientIdError**
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Missing required parameter: refresh_token

**Comment by blohinn** [comment]
Ohhh..
Solution:
```
google_blueprint = make_google_blueprint(
    client_id='',
    client_secret='',
    scope=['profile', 'email'],
    offline=True
)
```
**offline=True** fix my problem..
Man you make awesome lib, but why you didnt write about this trick? Or you wrote, but I didnt find?

**Comment by singingwolfboy** [comment]
@blohinn It’s documented here: http://flask-dance.readthedocs.io/en/latest/providers.html#module-flask_dance.contrib.google

Is there a better place to document this? I’d really appreciate it if you could make a pull request to improve the documentation, rather than just criticizing it!
