### ISSUE TITLE
How i can refresh my access_token manualy?

### ISSUE THREAD

**Issue by blohinn** [singingwolfboy/flask-dance#105]
Man, your lib work fine, but i have a trouble :(
How do you refresh the token? I try search answer in doc, but didnt find..
For example: my user successfull logined with flask dance. In my DB a have a dict:
```
{
    "access_token" : "ya29.Gl...O8",
    "expires_in" : 3599,
    "id_token" : "eyJhb...Sf8zr5kAE-0HKf67UlgA",
    "token_type" : "Bearer",
    "expires_at" : 1510427464.66068,
    "refresh_token" : "1/ybsh5gTXrcdz...zdZT8AUD"
}
```
And autorefreshing works fine. But how it work? It's a magic?! Where you are updating token?

Now, i want to use [gspread]( https://github.com/burnash/gspread) to work with Google Sheets. I made a custom credentials class and it's not a big problem. But it works only if my access_token not expired. 

And how i can refresh my token with your lib or manualy? Thanks for answer and sorry for my bad English!

**Comment by singingwolfboy** [comment]
The OAuth token refresh is implemented in [requests-oauthlib](https://requests-oauthlib.readthedocs.io/en/latest/examples/real_world_example_with_refresh.html), one of Flask-Dance's dependencies. [Here's the code, if that helps.](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L332-L350)

**Comment by blohinn** [comment]
Thanks!
But what do you think about this simply solution?
```
u = users_collection.find_one({'_id': ObjectId(user_id), 'oauth.provider': 'google'})

payload = {
    'grant_type': 'refresh_token',
    'client_id': current_app.config['GOOGLE_API_CLIENT_ID'],
    'client_secret': current_app.config['GOOGLE_API_CLIENT_SECRET'],
    'refresh_token': u['oauth']['token']['refresh_token']
}
r = requests.post(current_app.config['GOOGLE_API_REFRESH_TOKEN_URL'], data=payload)
r = r.json()
users_collection.update_one({'_id': ObjectId(user_id)}, {'$set': {
    'oauth.token.access_token': r['access_token'],
    'oauth.token.id_token': r['id_token'],
    'oauth.token.expires_at': time.time() + float(r['expires_in'])
}})
```

**Comment by singingwolfboy** [comment]
If it works for you, then great! I'm not going to critique the code of an unrelated project. :)

**Comment by blohinn** [comment]
Haha))
Thank you for help :)
