### ISSUE TITLE
Any way to use this with JWT

### ISSUE THREAD

**Issue by runar-rkmedia** [singingwolfboy/flask-dance#113]
Currently, it seems this only works with sessions stored as cookies. Any way to make it work with JWT?

**Comment by singingwolfboy** [comment]
I have no idea — I’ve never tried. Can you describe what sort of API you’d like to see for this? Maybe we can design/implement it together 😃

**Comment by runar-rkmedia** [comment]
I'm actually just getting started with JWT. As per my understanding, with JWT, there is no need for saving cookies at all, so it is easier to use it cross-domain without modifying the headers.

I don't really have much experience with the security aspect of this, but I could have a quick look at it. Needs to be marked highly experimental.

**Comment by runar-rkmedia** [comment]
Actually, never mind this. I have totally misunderstood the use-case for JWT. It is not supposed to be used as session-keys. 

I think this issue can be closed.
