### ISSUE TITLE
GitLab OAuth providor, client MissingTokenError before requesting token 

### ISSUE THREAD

**Issue by jgeorgeson** [singingwolfboy/flask-dance#115]
I'm writing Flask app to drive some GitLab workflows that aren't supported by their API. I don't really need to have a user database/profile in my app. My app just needs to fetch the list of GitLab groups that the user has access to, they select a group, and then my app will make API calls and splinter/selenium calls to perform the workflow. I've configured my application in GitLab per this doc

https://docs.gitlab.com/ee/integration/oauth_provider.html#oauth-applications-in-the-admin-area

I've setup a OAuth2ConsumerBlueprint object with the client ID/secret and URLs for authorization and tokens, according to this doc

https://docs.gitlab.com/ee/api/oauth2.html

When I click on the `<a href={{url_for("oauth-gitlab.login")}}>Login with GitLab</a>` link in my app, it takes me to my GitLab instance to login and asks me to approve, then it redirects me back to my app and that throws `oauthlib.oauth2.rfc6749.errors.MissingTokenError`. 

```
File "/home/jgeorgeson/Code/Dev-Engineering/gitlab-import-wrapper/import-wrapper/lib/python3.6/site-packages/flask_dance/consumer/oauth2.py", line 234, in authorized
**self.token_url_params
File "/home/jgeorgeson/Code/Dev-Engineering/gitlab-import-wrapper/import-wrapper/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
self._client.parse_request_body_response(r.text, scope=self.scope)
File "/home/jgeorgeson/Code/Dev-Engineering/gitlab-import-wrapper/import-wrapper/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 408, in parse_request_body_response
self.token = parse_token_response(body, scope=scope)
File "/home/jgeorgeson/Code/Dev-Engineering/gitlab-import-wrapper/import-wrapper/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
validate_token_parameters(params)
File "/home/jgeorgeson/Code/Dev-Engineering/gitlab-import-wrapper/import-wrapper/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 389, in validate_token_parameters
raise MissingTokenError(description="Missing access token parameter.")
```

Based on the 2nd gitlab.com link it seems like flask should be making a call to the token URL using the code returned by the authorization URL, but is instead expecting the token to be in the response already.

**Comment by singingwolfboy** [comment]
That's strange. Do you have a minimal test case that I can use to reproduce the problem?

**Comment by jgeorgeson** [comment]
I just followed the [custom provider](http://flask-dance.readthedocs.io/en/latest/providers.html#custom) in the docs. The `OAUTH_CLIENT_*` from my config is set from adding my app to GitLab per the 1st GitLab doc link and the `OAUTH_*_URL` are set per the 2nd GitLab doc link.

```python
app = Flask(__name__)
app.config.from_object('config')
gitlab_blueprint = OAuth2ConsumerBlueprint(
    "oauth-gitlab", __name__,
    client_id=app.config['OAUTH_CLIENT_ID'],
    client_secret=app.config['OAUTH_CLIENT_SECRET'],
    base_url=app.config['OAUTH_BASE_URL'],
    token_url=app.config['OAUTH_TOKEN_URL'],
    authorization_url=app.config['OAUTH_AUTH_URL']
)
app.register_blueprint(gitlab_blueprint, url_prefix='/login')

@app.route('/')
def root():
    if not gitlab_blueprint.session.authorized:
        return render_template('index.html')
    else:
        return redirect(url_for('welcome'))

@app.route('/welcome')
def welcome():
    resp = gitlab_blueprint.session.get('/user')
    assert resp.ok
    return "Welcome, {}".format(resp.content)
```
and my index.html template is

```
<a href="{{ url_for("oauth-gitlab.login") }}">Login with GitLab</a>
```

I can see in the output 

10.0.0.5 - - [02/Mar/2018 20:49:59] "GET / HTTP/1.1" 200 -
10.0.0.5 - - [02/Mar/2018 20:50:01] "GET /login/oauth-gitlab HTTP/1.1" 302 -
10.0.0.5 - - [02/Mar/2018 20:50:04] "GET /login/oauth-gitlab/authorized?code=[snip]&state=[snip] HTTP/1.1" 500 -
[Missing access token parameter exception stacktrace]

**Comment by singingwolfboy** [comment]
I was able to make the GitLab API work just fine. Here's my code:

```python
import os
from werkzeug.contrib.fixers import ProxyFix
from flask import Flask, redirect, url_for, jsonify
from flask_dance.consumer import OAuth2ConsumerBlueprint

app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)
app.secret_key = os.environ.get("FLASK_SECRET_KEY", "supersekrit")
app.config["GITLAB_OAUTH_CLIENT_ID"] = os.environ.get("GITLAB_OAUTH_CLIENT_ID")
app.config["GITLAB_OAUTH_CLIENT_SECRET"] = os.environ.get("GITLAB_OAUTH_CLIENT_SECRET")

gitlab_bp = OAuth2ConsumerBlueprint(
    "gitlab", __name__,
    base_url="https://gitlab.com/api/v4/",
    authorization_url="https://gitlab.com/oauth/authorize",
    token_url="https://gitlab.com/oauth/token",
)
gitlab_bp.from_config["client_id"] = "GITLAB_OAUTH_CLIENT_ID"
gitlab_bp.from_config["client_secret"] = "GITLAB_OAUTH_CLIENT_SECRET"
app.register_blueprint(gitlab_bp, url_prefix="/login")

@app.route("/")
def index():
    if not gitlab_bp.session.authorized:
        return redirect(url_for("gitlab.login"))
    resp = gitlab_bp.session.get("user")
    assert resp.ok
    return "You are @{username} on GitLab".format(username=resp.json()["username"])

if __name__ == "__main__":
    app.run()
```

Does that work for you? If so, would you like to be the maintainer of a GitLab pre-set configuration for Flask-Dance? (It's best to have the maintainer be someone who is actually _using_ the code.)

**Comment by jgeorgeson** [comment]
Well that works. :) My main issue was a stinking typo in the token URL ( ouath vs oauth ). After that I had misunderstood the `base_url`. I hadn't set it to the REST API base URL, but rather my on-prem instance's version of https://gitlab.com. Secondary to that, and contrary to the [custom provider example](http://flask-dance.readthedocs.io/en/latest/providers.html#custom) in the docs, "it" (flask-dance? requests_oauthlib?) doesn't seem to like leaving the trailing '/' off the base URL even if it's included as a leading '/' in `gitlab_bp.session.get("/user")`, as that produces a JSON decode error.

I can take a swag at contributing a preset now that I have a better idea.
