### ISSUE TITLE
Is it possible to use an application factory

### ISSUE THREAD

**Issue by scbunn** [singingwolfboy/flask-dance#117]
Is it possible to use an application factory without `@oauth_authorized.connect_via` being part of `create_app`?  I'm probably missing something, but I'm not seeing a way and I really don't want to have auth login as part of create_app.

**Comment by scbunn** [comment]
I figured this out; I had two hangups before.

1. I couldn't find it in the documentation, but the google auth code already has hooks into app.config
2. Moved the blueprint to a global

If anybody else is confused, I setup a small example outline that hopefully will help.
https://github.com/scbunn/flask-dance-example

**Comment by singingwolfboy** [comment]
@scbunn Thanks! Maybe you could make a pull request to [the documentation](https://github.com/singingwolfboy/flask-dance/tree/master/docs), and help improve it?

**Comment by scbunn** [comment]
Of course, I started on something but I need to brush on my RST :)

**Comment by singingwolfboy** [comment]
Awesome! [Sphinx has a great reference on reStructuredText.](http://www.sphinx-doc.org/en/master/rest.html) Let me know if I can help!

**Comment by abprojects** [comment]
Thanks for sharing on the application factory, really helped me out. 

Did you have issues with getting the "Cannot get OAuth token without associated user" error thrown while using application factory? My app uses application factory, and I restructured based on your example hoping to get rid of this error but it's still there. For some reason my @oauth_authorized.connect_via subscriber isn't being read and I can't figure out why? I've tried all the solutions from here and anything on the web and in the docs but nothing seems to work.

**Comment by singingwolfboy** [comment]
Have you read [the documentation about multi-user setups](https://flask-dance.readthedocs.io/en/latest/multi-user.html)? Does it address your questions at all?

> For some reason my @oauth_authorized.connect_via subscriber isn't being read and I can't figure out why?

Are you importing the file where this subscriber is defined?

**Comment by abprojects** [comment]
I read and tried the code on mult-user setups. It addresses my question but I had no luck in getting it to work when I try to structure my code in this way and when I structure it with the application factory example. I might be missing something. I'll try to post as much of what I have written so far:

 My application is setup like so:

-app
    -config.py (I have api key and api secret in this file)
-app
    -__init__.py (twitter blueprint created as global. both blueprints registered in create_app function)
    -models.py (OAuth class)
-auth
   -__init__.py (blueprint created, views imported)
   -views.py(subscriber func)

here is some of the code from the function in views.py:

from peak import twitter_blueprint 
from flask_dance.consumer import oauth_authorized, oauth_error
from peak.models import User, Role, TrainerProfile, AthleteProfile,\
        login_manager, OAuth, db
from . import auth

@oauth_authorized.connect_via(twitter_blueprint)
def tweet_logged_in(blueprint, token):
    if not token:
        flash('Failed to log in with Twitter.')
        return False
    
    resp = blueprint.session.get("account/settings.json")
    
    e = resp.json()["email"]
    name_full = resp.json()["name"]
    pro_id = resp.json()["id_str"]
    l = resp.json()["location"]

    s = None
    f = None
    lt = None
    
    if name_full is not None:
        s = name_full.split(" ")
        f = s[0]
        lt = s[1]
    
    q = OAuth.query.filter_by(provider=tl.name).filter_by(provider_user_id=pro_id).first()
    
    if q is None:
        q = OAuth(provider=tl.name, provider_user_id=pro_id, token=token)
    
    if q.user:
        login_user(q.user)
        flash('Successfully signed in with Twitter')
        if q.user.roles[0].id == 1:
            return redirect(url_for('trainer.dash', tid=q.user.id))
        elif q.user.roles[0].id == 2:
            return redirect(url_for('athlete.athlete_home', aid=q.user.id))
        else:
            return redirect(url_for('auth.oauth_role_ver'))
    else:
        new = User(email=e, first_name=f, last_name=lt,  active=True, confirm_at = datetime.utcnow(), login_count = 1, )
        q.user = new
        db.session.add_all([new, q])
        db.session.commit()
        login_user(new)
        flash('Successfully signed in with Twitter')
        return redirect(url_for('auth.oauth_role_ver'))
    
    return False

In the template I have the login link set to 'twitter.login'. Everything else is set up pretty identical to the example for the application factory. Am I missing something obvious?

**Comment by abprojects** [comment]
Sorry, it didn't post the way I intended format wise, but the application set up should read as config under app, __init__, models, auth under the second app and __init__, views under auth. Sorry I am a noob in formatting on here. Let me know if anything is unclear
