### ISSUE TITLE
GitHub: oauthlib.oauth2.rfc6749.errors.MissingTokenError

### ISSUE THREAD

**Issue by jononomo** [singingwolfboy/flask-dance#122]
I am getting this error and I can't figure out why.

I am using this approach:

```
blueprint = make_github_blueprint(
	client_id=environ['FLASK_GITHUB_CLIENT_ID'],
	client_secret=environ['GITHUB_CLIENT_SECRET']
)
app.register_blueprint(blueprint, url_prefix="/login")

@app.route("/")
def index():
    if not github.authorized:
        return redirect(url_for("github.login"))
    resp = github.get("/user")
    assert resp.ok
    return "You are @{login} on GitHub".format(login=resp.json()["login"])
```

I have `/etc/hosts` set up so that `local.my-app.io` goes to `127.0.0.1`

If I go to a new incognito window and then visit `local.my-app.io:5000` in my browser after launching things with `flask run`, then I get redirected to the github login page as expected, where I have registered an app with callback of: `http://local.my-app.io:5000/login/github/authorized`

After logging in successfully I get redirected to a page where I see a crash and a stacktrace telling me: 

`oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.`

**Comment by singingwolfboy** [comment]
It sounds like GitHub is not passing the access token back to your application. This is a vital part of the OAuth dance, and it's not something that the OAuth consumer (your application) has any control over. Check on GitHub and see if there's some reason why it's not giving you the access token.

**Comment by precipice** [comment]
Hm, I'm also seeing this error with the Slack blueprint, and I saw this as well: https://stackoverflow.com/questions/50716353/flask-dance-with-facebook-api-missing-access-token-parameter

Have you gotten other reports on this issue? I'll keep digging.

**Comment by precipice** [comment]
Oh, lol, I figured it out right after submitting the comment.

I was using the wrong value for the blueprint's `client_secret` parameter. Slack has both a "client secret" and a "signing secret" and I mixed them up.
