### ISSUE TITLE
Twitter Oauth cancel crash

### ISSUE THREAD

**Issue by chuyachia** [singingwolfboy/flask-dance#125]
When entered Twitter Oauth page and clicked"Cancel" instead of "Authorize app", Twitter propose a button to return to the original app which actually redirects to "/twitter/authorized?denied=xxxx". 
![image](https://user-images.githubusercontent.com/25123789/39789771-f744c788-52ff-11e8-87f3-1cbce73c2225.png)
 
This calls the _authorized_ method defined in _oauth1.py_. However, the fact that the redirect url only contains a _denied_ key and does not have an _oauth_token_ key causes `self.session.parse_authorization_response(request.url)` to crash.
What do you think if we add
`if 'denied' in request.args: 
return redirect("/")`
just before calling self.session.parse_authorization_response?

**Comment by singingwolfboy** [comment]
Fixed by #127
