### ISSUE TITLE
Possible to run without OAUTHLIB_INSECURE_TRANSPORT?

### ISSUE THREAD

**Issue by charlesreid1** [singingwolfboy/flask-dance#129]
In the [Github example](http://flask-dance.readthedocs.io/en/latest/quickstarts/github.html) the page states:

> When you run this code, you must set the OAUTHLIB_INSECURE_TRANSPORT environment variable for it to work.

Why?

It then states

> Do NOT set OAUTHLIB_INSECURE_TRANSPORT in production.

Does this mean the Github example cannot be used at all in production, ever (excepting Heroku if you run the proxy middleware)? Or is it designed/intended to be run with the proxy middleware as the default setup to keep it secure?

Any clarification is appreciated.

**Comment by singingwolfboy** [comment]
Hi @charlesreid1, thanks for bringing this up! Sorry for the confusion.

Flask-Dance is built on top of [`oauthlib`](https://oauthlib.readthedocs.io/), a Python toolkit that implements the OAuth specifications. The specification for OAuth 2 requires that all communication _must_ occur over secure HTTPS -- if any communication occurs over insecure HTTP, it's vulnerable to attack. As a result, `oauthlib` raises an error if you use insecure HTTP. However, most people don't want to spend the time and effort to configure secure HTTPS for doing local testing -- it's only a problem for production, not for development.

As a result, `oauthlib` allows you to disable this check. If you set the [`OAUTHLIB_INSECURE_TRANSPORT`](https://oauthlib.readthedocs.io/en/latest/oauth2/security.html#envvar-OAUTHLIB_INSECURE_TRANSPORT) environment variable, it will _not_ check for secure HTTPS, and allow the OAuth dance to continue whether or not it is secure. Disabling this check is intended only for development, _not_ for production -- in production, you _must_ configure secure HTTPS to make sure communication happen securely.

So, that's the origin of the warning in the documentation. Is it more understandable now? And can you think of a good way to explain all of this in the Flask-Dance documentation, _without_ making the explanation so long that most people won't bother to actually read it?

**Comment by charlesreid1** [comment]
> most people don't want to spend the time and effort to configure secure HTTPS for doing local testing -- it's only a problem for production, not for development.

Bingo! I understand now. I think _local_ is more clear than _production_. (I run remote servers but do not consider much of what I do "production".)

As for clarifying [the docs](http://flask-dance.readthedocs.io/en/latest/quickstarts/github.html), it would be more clear if it said,

> When you run this code **locally (without HTTPS enabled),** you must set the OAUTHLIB_INSECURE_TRANSPORT environment variable for it to work.

Same with the warning: using local as the reference, rather than production, makes things more clear:

> Do NOT set OAUTHLIB_INSECURE_TRANSPORT in production

to 

> OAUTHLIB_INSECURE_TRANSPORT should only be set for local testing.

This isn't rigorously correct if you think about testing over trusted networks and so it's not as "correct" as production, if you think of production as, more generally, whatever is not testing, but just my $0.02.

**Comment by charlesreid1** [comment]
P.S. - thanks for this library, it's is a great idea and well-executed! Plus it helps me avoid using Ruby  😁

**Comment by singingwolfboy** [comment]
Looks like this issue is resolved! Thanks for the pull request 😄
