### ISSUE TITLE
MismatchingStateError

### ISSUE THREAD

**Issue by samanyougarg** [singingwolfboy/flask-dance#132]
Hi there

Thanks for creating flask-dance. It's a fantastic library.
I am using flask-dance in my production app. It was working perfectly before but suddenly started giving this error - 
`oauthlib.oauth2.rfc6749.errors.MismatchingStateError: (mismatching_state) CSRF Warning! State not equal in request and response.`

Here's the complete log - 
`[2018-05-28 16:02:29,857] ERROR in app: Exception on /google_login/google/authorized [GET]
May 28 16:02:29 radhakrishna gunicorn[19709]: Traceback (most recent call last):
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/flask/app.py", line 2284, in wsgi_app
May 28 16:02:29 radhakrishna gunicorn[19709]:     response = self.full_dispatch_request()
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/flask/app.py", line 1807, in full_dispatch_request
May 28 16:02:29 radhakrishna gunicorn[19709]:     rv = self.handle_user_exception(e)
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 273, in error_router
May 28 16:02:29 radhakrishna gunicorn[19709]:     return original_handler(e)
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/flask/app.py", line 1710, in handle_user_exception
May 28 16:02:29 radhakrishna gunicorn[19709]:     reraise(exc_type, exc_value, tb)
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
May 28 16:02:29 radhakrishna gunicorn[19709]:     raise value
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/flask/app.py", line 1805, in full_dispatch_request
May 28 16:02:29 radhakrishna gunicorn[19709]:     rv = self.dispatch_request()
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/flask/app.py", line 1791, in dispatch_request
May 28 16:02:29 radhakrishna gunicorn[19709]:     return self.view_functions[rule.endpoint](**req.view_args)
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/flask_dance/consumer/oauth2.py", line 246, in authorized
May 28 16:02:29 radhakrishna gunicorn[19709]:     **self.token_url_params
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 187, in fetch_t
May 28 16:02:29 radhakrishna gunicorn[19709]:     state=self._state)
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/web_application.py", line
May 28 16:02:29 radhakrishna gunicorn[19709]:     response = parse_authorization_code_response(uri, state=state)
May 28 16:02:29 radhakrishna gunicorn[19709]:   File "/home/radhakrishna/radhakrishna/venv/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 230, in parse
May 28 16:02:29 radhakrishna gunicorn[19709]:     raise MismatchingStateError()
May 28 16:02:29 radhakrishna gunicorn[19709]: oauthlib.oauth2.rfc6749.errors.MismatchingStateError: (mismatching_state) CSRF Warning! State not equal in request and response.`

Please let me know how I can fix this error.

Thanks

**Comment by singingwolfboy** [comment]
In the OAuth dance, the `state` parameter is used to prevent CSRF (cross-site request forgery) attacks. The consumer makes up a random string and sends it to the provider when starting the dance, and expects the provider to return exactly the same string at the end of the dance. If the provider can't do so, that probably indicates that some sort of attack is going on, and the consumer might not be talking to the server it expects to be talking to. [Here's some documentation about how authorization works with OAuth 2, which mentions this `state` parameter.](https://www.oauth.com/oauth2-servers/authorization/the-authorization-request/)

If this exception suddenly started happening, without you making any modifications to your code, then that is _very_ suspicious. Maybe the OAuth provider made a change on their end, and caused a bug with how the `state` parameter is returned. Or maybe something else is going on that's less innocent.

However, regardless of the reason, if this is causing the website to crash, then that seems like a problem. If a `MismatchingStateError` occurs, the application should detect that, treat the authorization as unsuccessful, and display a warning to the user that OAuth isn't working properly right now. Do you have a suggestion on how we can modify the project to make that possible, without opening a security hole in the project?

**Comment by samanyougarg** [comment]
Thanks for the detailed response.

I checked the state parameter in the URLs before and after authorization and found that they are not the same. I am getting the same error for google, facebook and Github logins.

Below is the code I am using for github. Please have a look and let me know if I am doing something wrong. Thanks.

```
  @oauth_authorized.connect_via(github_blueprint)
  def github_logged_in(blueprint, token):
    if not token:
        flash("Failed to log in with GitHub.", category="error")
        return False

    resp = blueprint.session.get("/user")
    if not resp.ok:
        msg = "Failed to fetch user info from GitHub."
        flash(msg, category="error")
        return False

    github_info = resp.json()
    github_user_id = str(github_info["id"])

    # Find this OAuth token in the database, or create it
    query = OAuth.query.filter_by(
        provider=blueprint.name,
        provider_user_id=github_user_id,
    )
    try:
        oauth = query.one()
    except NoResultFound:
        oauth = OAuth(
            provider=blueprint.name,
            provider_user_id=github_user_id,
            token=token,
        )

    user = User.query.filter_by(email=github_info["email"]).first()

    if oauth.user:
        login_user(oauth.user)
        flash('You are now logged in. Welcome back!', 'success')
        return redirect(request.args.get('next') or url_for('main.index'))

    elif user:
        login_user(user, True)
        flash('You are now logged in. Welcome back!', 'success')
        return redirect(request.args.get('next') or url_for('main.index'))

    else:
        # Create a new local user account for this user
        max_id = db.session.query(db.func.max(User.id)).scalar()
        user = User(
            id=max_id+1,
            email=github_info["email"],
            social_id=github_info["id"],
            social_provider="github",
            username=github_info["login"],
            first_name=github_info["name"],
            confirmed=True)
        # Associate the new local user account with the OAuth token
        oauth.user = user
        # Save and commit our database models
        db.session.add_all([user, oauth])
        db.session.commit()
        # Log in the new local user account
        login_user(user, True)
        flash('You are now logged in. Welcome!', 'success')
        return redirect(request.args.get('next') or url_for('main.index'))

    # Disable Flask-Dance's default behavior for saving the OAuth token
    return False


@oauth_error.connect_via(github_blueprint)
def github_error(blueprint, error, error_description=None, error_uri=None):
    msg = (
        "OAuth error from {name}! "
        "error={error} description={description} uri={uri}"
    ).format(
        name=blueprint.name,
        error=error,
        description=error_description,
        uri=error_uri,
    )
    flash(msg, category="error")

**Comment by singingwolfboy** [comment]
Your code seems reasonable to me: I don't see anything obviously wrong with it.

> I checked the state parameter in the URLs before and after authorization and found that they are not the same.

Then it sounds like this error is being raised correctly.

> I am getting the same error for google, facebook and Github logins.

That's _really_ weird -- I wouldn't expect any of those providers to have a problem with this `state` parameter, let alone all three at once. Are you sure you didn't change anything about your code?

For debugging purposes, the `state` is [saved in the Flask session cookie](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L189) in the `login` view, and [pulled from the Flask session cookie](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L230) in the `authorized` view. Maybe you're doing something weird that would affect that, somehow?

**Comment by singingwolfboy** [comment]
Minor critique of your code: why are you saving `social_provider` and `social_id` in your `User` model? They are already saved in your `OAuth` model, which is associated with your `User` model. This separation also allows your users to be associated with more than one OAuth provider simultaneously -- one user can be link their Google, Facebook, and GitHub accounts to your website, and log in with any of them.

**Comment by samanyougarg** [comment]
Thanks for checking out the code. I set up flask-dance again from scratch for Github and it seems to be working now.
I am saving social_provider and social_id because I was using another package for social login before using flask-dance and was saving the information in the same table.
