### ISSUE TITLE
SQLAlchemy Multi-User Quickstart - provider_user_id getting changed to null after a few days (Google)

### ISSUE THREAD

**Issue by McSpidey** [singingwolfboy/flask-dance#135]
Hi

I've been following this guide (https://flask-dance.readthedocs.io/en/latest/quickstarts/sqla-multiuser.html) exactly, but with the Google blueprint swapped in, and noticed it all works fine to start with - except after a few days after logging in/out sucesfully a few times, then letting it be idle, the provider_user_id suddenly gets changed to Null on a subsequent login. This means the Oauth query fails to find the record, and it attempts to make a new contact, which fails due to the Unique flag.

I've come up with a workaround for checking the User lookup based on the username/email, and to also check if the provider_user_id is blank, then update it from the new login session data, but I'd really like to try and understand why it's going to null intermitently at all in the first place. My suspicion is maybe it's part of an invisible token refresh? I'm using offline=True and reprompt_consent=True in the blueprint as per other suggestions found here in the issues list.

I'd like a working example for multi user "Login with Google" authentication, with token refresh, if anyone has written one?

**Comment by singingwolfboy** [comment]
I have no idea what the problem is here, but I just want to mention that if someone does want to write some documentation for how to set up multiuser authentication with Google, and sends a pull request, I'd be happy to merge it and pull it into the official docs 😸

**Comment by McSpidey** [comment]
Here's my work-around code, however I'm posting it with a caveat I'm not convinced I have a working flow since I've noticed in testing users are sometimes getting some form of cached login from another user (not good)...

It lives inside this function:
# create/login local user on successful OAuth login
@oauth_authorized.connect_via(blueprint)
def google_logged_in(blueprint, token):

--
# Find this OAuth token in the database, or create it
    query = OAuth.query.filter_by(
        provider=blueprint.name,
        provider_user_id=google_user_id,
    )
    try:
        oauth = query.one()
    except NoResultFound:
        #Workaround for null provider_user_id
        try:
            #Get user based on email
            query = User.query.filter_by(email=google_email)
            user = query.one()
            #Get Oauth
            query = OAuth.query.filter_by(
                user=user
            )
            oauth = query.one()
            if not oauth.provider_user_id:
                oauth.provider_user_id = google_user_id
            db.session.add(oauth)
            db.session.commit()
        except:
            oauth = OAuth(
                provider=blueprint.name,
                provider_user_id=google_user_id,
                token=token,
            )
--

**Comment by McSpidey** [comment]
Since I first opened this ticket I see someone has been very active in trying to sort out Google flow bugs. I'm incredibly excited to see this and hope once complete they write a working example for Google multi-user :)

**Comment by shkkim** [comment]
I'm facing the same problem, do you know if the bug has been fixed?

**Comment by McSpidey** [comment]
I never reached the point of confidence but haven't tested lately. My guess remains the same, that there isn't a bullet proof tutorial on how to set it up.

**Comment by shkkim** [comment]
Thanks for the response and solution - ended up using a similar solution to your's
