### ISSUE TITLE
Spotify blueprint remains unauthorized after successful oauth_authorized.connect_via signal

### ISSUE THREAD

**Issue by kvsingh** [singingwolfboy/flask-dance#136]
Hi,

I have created an implementation for oauth_authorize.connect_via signal, as mentioned [here](https://flask-dance.readthedocs.io/en/latest/quickstarts/sqla-multiuser.html)

```
@oauth_authorized.connect_via(spotify_blueprint)
def spotify_logged_in(blueprint, token):
    if not token:
        print "Failed to log in with Spotify."
        return False
    resp = blueprint.session.get("v1/me")
    if not resp.ok:
        msg = "Failed to fetch user info from spotify."
        print msg
        return False
    spotify_info = resp.json()
    spotify_user_id = str(spotify_info["id"])
    print spotify.authorized 
    query = OAuth.query.filter_by(
        spotify_id=spotify_user_id,
    )
    try:
        oauth = query.one()
    except NoResultFound:
        oauth = OAuth(
            spotify_id=spotify_user_id,
            token=token,
        )

    if oauth.user:
        login_user(oauth.user)
        print "Successfully signed in with Spotify."
    else:
        user = User()
        oauth.user = user
        db.session.add_all([user, oauth])
        db.session.commit()
        login_user(user)
        print "Successfully signed in with Spotify."
    return False
```
The logs contain "Successfully signed in with Spotify.", and my db contains an oauth object with the access token.

However, after login, spotify redirects the app to a particular url on my application. In the view of this page, doing the following:
`print spotify_blueprint.authorized()`
gives me 
`{u'error': {u'status': 401, u'message': u'No token provided'}}`

So, it seems that the login is successful, but the handler for the page which spotify redirects to tells me that the user is not authorized.

Any idea what could be going wrong?
Thanks.

**Comment by singingwolfboy** [comment]
@nickdirienzo, you're the maintainer for the Spotify provider. Do you know anything about why this might be happening?

**Comment by nickdirienzo** [comment]
Sorry this took me a few days to get to, @singingwolfboy.

@kvsingh I haven't been keeping tabs on this project as closely as I used to because I haven't been working on my side project in quite some time. I wonder if your `return False` at the end of the function is causing it to always think it's not authorized? I don't really have a go-to answer here, unfortunately—sorry about that. Have you been able to resolve your issue?

For what it's worth, my implementation looks like:
```
@oauth_authorized.connect_via(spotify_blueprint)
def spotify_logged_in(blueprint, token):
    resp = blueprint.session.get('/v1/me')
    username = resp.json()['id']
    user = db.session.query(User).filter_by(username=username).first()
    if user is None:
        user = User(username=resp.json()['id'])
        db.session.add(user)
        db.session.commit()
    flask_login.login_user(user)
```

Whether or not that's correct is a different story but for my hobby project it was working okay. Happy to chat more if you'd like some help debugging!

**Comment by nickdirienzo** [comment]
Ah, I am quite wrong about the `return False` I referenced as that is expected in a multi-social-app setup, which I'm assuming you have and my example doesn't consider. Really sorry about the not-so-helpful reply. 

For transparency's sake, I might be slow to reply and I don't have time to reproduce this myself anytime soon, but if I can be helpful do let me know. @kvsingh I hope you've managed to make some progress and I'd love to hear how you've resolved this, if so 🤞

**Comment by kvsingh** [comment]
@singingwolfboy Removing `return False` from the `spotify_logged_in` function seems to have resolved the issue.

**Comment by nickdirienzo** [comment]
Woohoo. Glad you’re back to a good state :)
