### ISSUE TITLE
Advice on how to deal with testing

### ISSUE THREAD

**Issue by daenney** [singingwolfboy/flask-dance#138]
So I was looking at integrating flask-dance but I'm struggling to understand what to do when the app is being tested. In those cases I don't really want a "real" oauth provider, just enough for the app to think a user is logged in (and some necessary information).

What's the advice on how to do that?

**Comment by wgwz** [comment]
at the risk of being too vague and/or not understanding what you mean, you can use mock for the oauth object, i.e.:

    @app.route("/")
    def index():
        if not github.authorized:
            return redirect(url_for("github.login"))
        resp = github.get("/user")
        assert resp.ok
        return "You are @{login} on GitHub".format(login=resp.json())

i.e. you can mock the github when using the flask testing client and switch its authorized property to be truthy and falsy to test both code paths.

**Comment by daenney** [comment]
Ah yes, that's definetly a way of doing this. Thanks!
