### ISSUE TITLE
Having the access token in the url

### ISSUE THREAD

**Issue by Tadaboody** [singingwolfboy/flask-dance#142]
From what I've gathered, in a request to a providers api the access token is passed in the header.  

Some providers, such as instagram don't look for a token there and I keep getting the error that 
``{"code": 400, "error_type": "OAuthParameterException", "error_message": "Missing client_id or access_token URL parameter.'}``. 

I request the option to define a `OAuth2ConsumerBlueprint` that attaches the token in the url params instead of the header, so that the access to providers like instagram is the same as access to other providers with simply `bp.session.get(endpoint)`

**Comment by Tadaboody** [comment]
For reproducibility, the method to create the blueprint I use:
```py
def make_instagram_blueprint(
        client_id=None, client_secret=None, scope=None, redirect_url=None,
        redirect_to=None, login_url=None, authorized_url=None,
        session_class=None, backend=None)-> flask_dance.OAuth2ConsumerBlueprint:

    instagram_bp = flask_dance.OAuth2ConsumerBlueprint("instagram", __name__,
                                                       client_id=client_id,
                                                       client_secret=client_secret,
                                                       scope=scope,
                                                       base_url="https://api.instagram.com/v1/",
                                                       authorization_url="https://api.instagram.com/oauth/authorize/",
                                                       token_url="https://api.instagram.com/oauth/access_token",
                                                       redirect_url=redirect_url,
                                                       redirect_to=redirect_to,
                                                       login_url=login_url,
                                                       authorized_url=authorized_url,
                                                       session_class=session_class,
                                                      )
    instagram_bp.from_config["client_id"] = "INSTAGRAM_OAUTH_CLIENT_ID"
    instagram_bp.from_config["client_secret"] = "INSTAGRAM_OAUTH_CLIENT_SECRET"
    return instagram_bp


instagram_bp = make_instagram_blueprint(scope="basic")
instagram_bp.backend = flask_dance.SQLAlchemyBackend(
    OAuth, get_db().session, user=flask_login.current_user)
```
and the query is
```py
request = instagram_bp.session.get('users/self')
# query works if you add:   params={'access_token': instagram_bp.session.access_token})
```

**Comment by singingwolfboy** [comment]
The Slack API works this way as well, and it's implemented using a [compliance fix in Requests-OAuthlib](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/compliance_fixes/slack.py). In Flask-Dance, this compliance fix is [applied using the `session_created()` method on the blueprint](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/contrib/slack.py#L16-L18).

Could you try implementing an Instagram provider using this method, and let me know if it works? If it does, maybe you could submit a pull request to this project, so that others can use the Instagram API easily, as well.

**Comment by daenney** [comment]
It's been a while since we've heard anything about this. Given a solution has been presented I'm closing this issue for now. Feel free to re-open it if you need further help.

**Comment by Tadaboody** [comment]
Hi I'd like to contribute an instagram blueprint with a compliance fix like the one used in the slack blueprint. How would you reccomend I do the cross-repository pull request?

**Comment by singingwolfboy** [comment]
@Tadaboody You've got two options:

1. First implement the compliance fix in Requests-OAuthlib, send a pull request, and get it merged. Once it's merged in Requests-OAuthlib, implement the Instagram blueprint in Flask-Dance using that compliance fix, send a pull request, and get it merged.
2. Implement both the compliance fix and the Instagram blueprint in Flask-Dance. Once it's working properly, we can backport the compliance fix into Requests-OAuthlib, and remove it from Flask-Dance.

Which would you prefer?
