### ISSUE TITLE
How to logout - unauthorize?

### ISSUE THREAD

**Issue by Darthholi** [singingwolfboy/flask-dance#145]
All the examples mention how to add blueprint, check for authorization and authorize if needed. Is there any way to programatically (in my own logout function) clear the session to let user login(authorize) again?
Thanks!

**Comment by daenney** [comment]
Yes, you can absolutely do this. What you need to do is delete the token from the session. If you're not using the SQLAlchemy backend but going through Flask and it's default cookie-based session storage, you can do something like: `del current_app.blueprints['google'].token`.

Depending on what you want you to achieve you can also revoke the token itself, though this is provider dependent. If you do that they'll be presented with a consent screen next time they login.

Finally, after having removed the token you could also call a `session.clear()` to clear anything else in your session.

**Comment by daenney** [comment]
One thing, if you do this but you use something like a `@login_required` decorator on every page, including `/` the user will automatically get logged back in again as it'll trigger the OAuth flow, they've already given consent and done. In that case you'd have to revoke the token first.

It's also important to note that if they've already given consent but you want them to be able to switch account (perhaps they have multiple and they picked the wrong one) just deleting the token won't work, you'll have to call the OAuth provider's token revocation endpoint first, or force them to go through the consent screen every time.

**Comment by daenney** [comment]
I'm going to close this issue as we haven't heard back in a while. If you need further help with this feel free to re-open the issue.

**Comment by ohenrik** [comment]
I struggled a bit with this as i did not find any clear examples of how to revoke the token from google. However i managed to get it working with this code:

```python
@app.route("/logout")
def logout():
    resp = google.post(
        'https://accounts.google.com/o/oauth2/revoke',
        params={'token': app.blueprints['google'].token["access_token"]},
        headers = {'content-type': 'application/x-www-form-urlencoded'}
    )
    if resp.ok:
        del app.blueprints['google'].token
        session.clear()
        logout_user()
    return redirect(url_for("index"))
```

@daenney Please let us know if there are better ways to implement this logout logic (Especially if there are any security holes in this logic).

**Comment by daenney** [comment]
You could check if you're `google.authorized` first. If your token has expired for example the call to `google.post` will fail with something like an `InvalidClentError` when using online tokens.

`session.clear()` will already remove the token as it nukes everything in the session, so there's no need for the `del` before it.

Other than that, looks good!

**Comment by ohenrik** [comment]
Perfect! Thank you for answering! :))

**Comment by hammer2383** [comment]
` resp = google.post(
        'https://accounts.google.com/o/oauth2/revoke',
        params={'token': app.blueprints['google'].token["access_token"]},
        headers = {'content-type': 'application/x-www-form-urlencoded'}
    )
`
beginner here 
can you guys give me a document about that line ?or explain it to me
Sorry to ask

**Comment by singingwolfboy** [comment]
@hammer2383 can you check out the document in #177, and let me know if it's understandable for you? (Please comment on that pull request, _not_ on this GitHub issue.)

**Comment by imasish** [comment]
hello,i am doing
@app.route("/logout")
def logout():
    
    token = google_blueprint.token["access_token"]
    resp = google.post(
        "https://accounts.google.com/o/oauth2/revoke",
        params={"token": token},
        headers={"Content-Type": "application/x-www-form-urlencoded"}
    )
    assert resp.ok, resp.text
    logout_user()        # Delete Flask-Login's session cookie
    del google_blueprint.token  # Delete OAuth token from storage
    return redirect('/')

but token = google_blueprint.token["access_token"] showing none type is not subscripable
