### ISSUE TITLE
Consider bubbling oauth providers up

### ISSUE THREAD

**Issue by Bachmann1234** [singingwolfboy/flask-dance#15]
I can look into a PR for this if you like the idea....

So I have been playing with using flask-dance with facebook oauth (potential PR there as well)

Facebook has an... lets call it advanced... control panel for its apps. For a newbie it can be easy to make mistakes. Personally I found it difficult to debug these mistakes when using flask-dance.

So take redirect uri that's totally wrong! When I test my app I see this

![screen shot 2015-05-03 at 10 35 03 pm](https://cloud.githubusercontent.com/assets/1521093/7448344/4ac21368-f1e5-11e4-8082-fc01ff15e09a.png)

But thats absolutely useless to me. Dig into the source and there is a more useful error message lurking

![screen shot 2015-05-03 at 10 44 57 pm](https://cloud.githubusercontent.com/assets/1521093/7448373/11f02fc4-f1e6-11e4-84de-862f4bf5794c.png)

```'{"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request","type":"OAuthException","code":100}}'```

Now I know to fix my facebook app settings

![screen shot 2015-05-03 at 10 33 31 pm](https://cloud.githubusercontent.com/assets/1521093/7448382/2e0aca7a-f1e6-11e4-9b21-9bcfdf17349d.png)

Perhaps you can surface the response text when a request fails.

**Comment by singingwolfboy** [comment]
Definitely a good idea. Maybe we can put a try/except block around `self.session.fetch_token`, and have it throw a more useful exception with the response from the provider.

**Comment by Bachmann1234** [comment]
Yeah, sounds good. But im tired of code tonight. Ill make a note to address this sometime soon

**Comment by singingwolfboy** [comment]
Totally reasonable. Thank you so much for all your help on this! :sparkling_heart:
