### ISSUE TITLE
struggling to test flask-dance / flask-security / flask-sqlalchemy / pytest

### ISSUE THREAD

**Issue by louking** [singingwolfboy/flask-dance#150]
cross posted to https://stackoverflow.com/questions/51563223/struggling-to-test-flask-dance-flask-security-flask-sqlalchemy-pytest

My application requires login to google for later use of google apis. I have flask-dance, flask-security, flask-sqlalchemy working to the point where I can do the log in and log out in my development system.

What I've been struggling with is testing of the login using pytest. I am trying force the login with the call to flask_security.login_user, but test_login fails as if nobody is logged in. I suspect this is a problem because of context setting, but I have tried a lot of different things and haven't found the magic elixir.

Unfortunately, while I have a lot of experience in software development in general and python in particular, I don't have the pytest / flask-dance / flask-security background needed to solve this.

in settings.py

```python
class Testing():
    # default database
    SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'

    TESTING = True
    WTF_CSRF_ENABLED = False

    # need to set SERVER_NAME to something, else get a RuntimeError about not able to create URL adapter
    SERVER_NAME = 'dev.localhost'

    # need a default secret key - in production replace by config file
    SECRET_KEY = "<test secret key>"

    # fake  credentials
    GOOGLE_OAUTH_CLIENT_ID = 'fake-client-id'
    GOOGLE_OAUTH_CLIENT_SECRET = 'fake-client-secret'

    # need to allow logins in flask-security. see https://github.com/mattupstate/flask-security/issues/259
    LOGIN_DISABLED = False
```
in conftest.py

```python
import pytest

from racesupportcontracts import create_app
from racesupportcontracts.dbmodel import db
from racesupportcontracts.settings import Testing

@pytest.fixture
def app():
    app = create_app(Testing)
    yield app

@pytest.fixture
def dbapp(app):
    db.drop_all()
    db.create_all()
    yield app
```
in test_basic.py
```python
def login_test_user(email):
    from racesupportcontracts.dbmodel import db, User
    from flask_security import login_user
    user = User.query.filter_by(email=email).one()
    login_user(user)
    db.session.commit()

def test_login(dbapp):
    app = dbapp
    from racesupportcontracts.dbmodel import db, init_db
    from racesupportcontracts import user_datastore
    from flask import url_for
    # init_db should create at least superadmin, admin roles
    init_db(defineowner=False)
    useremail = 'testuser@example.com'
    with app.test_client() as client:
        create_user(useremail, 'superadmin')
        login_test_user(useremail)
        resp = client.get('/', follow_redirects=True)
        assert resp.status_code == 200
        assert url_for('admin.logout') in resp.data
```

**Comment by daenney** [comment]
We've recently added some documentation on how to do testing with Flask-Dance: https://flask-dance.readthedocs.io/en/latest/testing.html.

Could you read through that and see if it answers your questions? If not, what's missing?

**Comment by louking** [comment]
Yes, I've read that but I think the connection to flask-security is where I'm confused. I need to log in someone with a particular role to test certain views.

Also this seems to assume use of session cookies for oauth storage. I assume that I can just store the same credentials in the sqlalchemy database, but I'm stuck at getting the user logged in first.

Possibly I'm going about this all wrong to achieve my goal of testing that a view is only accessible to a user with specific (flask-security) role.

I was starting to think I have to patch google to trick flask-dance into logging me in properly using flask-security. If so I don't know what google api's I'd need to patch.

**Comment by singingwolfboy** [comment]
You can also use the [MemoryBackend](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/backend/__init__.py#L31) for testing purposes. It simplifies the situation when you don't actually care about testing where the OAuth data is stored and retrieved from, and [it's what the Flask-Dance tests do.](https://github.com/singingwolfboy/flask-dance/blob/master/tests/contrib/test_google.py)

**Comment by louking** [comment]
I think using sqlite:///:memory: achieves the same goal as MemoryBackend?

My main question is how do I trick flask-security into being logged in while using a google oauth process performed by flask-dance.

I'm sorry if I'm being dense here.

**Comment by singingwolfboy** [comment]
If you want to tell flask-security that a certain user is logged in, you call the [`login_user()`](https://flask-login.readthedocs.io/en/latest/#flask_login.login_user) function. Flask-Dance doesn't handle logging in users, it just identifies _which_ user should be logged in, based on the information that Google (or whatever OAuth provider you're using) provides. Once you know who should be logged in, you can `login_user()` to actually do that.

Does that help?

**Comment by louking** [comment]
Well that's what I'm trying to do, but it's not working. I suspect it's because I'm in the wrong context or something. Again apologies for my questions which are probably basic pytest questions.

Excerpted from my OP:

in test_basic.py
```
def login_test_user(email):
    from racesupportcontracts.dbmodel import db, User
    from flask_security import login_user
    user = User.query.filter_by(email=email).one()
    login_user(user)
    db.session.commit()

def test_login(dbapp):
    app = dbapp
    from racesupportcontracts.dbmodel import db, init_db
    from racesupportcontracts import user_datastore
    from flask import url_for
    # init_db should create at least superadmin, admin roles
    init_db(defineowner=False)
    useremail = 'testuser@example.com'
    with app.test_client() as client:
        create_user(useremail, 'superadmin')
        login_test_user(useremail)
        resp = client.get('/', follow_redirects=True)
        assert resp.status_code == 200
        assert url_for('admin.logout') in resp.data
```

**Comment by singingwolfboy** [comment]
Unfortunately, I'm not sure how to help you here. Were you able to figure this out on your own? If not, I think we need more information to try to solve this problem. The specific error message would probably help.

**Comment by louking** [comment]
I've been distracted by some other stuff which has pulled me away from this project. I hope to get back to the project in the next few weeks. I've been building without the tests for now but it's making me anxious, so when I get back to it and get to a good point I'll try to figure this out. When I do I plan to add to the flaskdance docs if it's appropriate.

**Comment by louking** [comment]
I guess this can be closed. I am working on other aspects of the application and (sorry to say) have not been paying much attention to unit testing. If I do come up with a solution I'll try to remember to post it hear and maybe issue documentation pull request.
