### ISSUE TITLE
login with facebook issue

### ISSUE THREAD

**Issue by leejoonsung007** [singingwolfboy/flask-dance#154]
I am quite confused about the redirect_url in login with facebook, facebook only allows the website with SSL certification to access it.  My website has been deployed with https, but I still get the error 

> Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https:// 

Then I checked the URL, it is

>  https://www.facebook.com/dialog/oauth?response_type=code&client_id=171456803533554&**redirect_uri=http%3A%2F%2Fmy_website_link%2Fauth%2Ffacebook%2Fauthorized**&scope=email&state=Zi8KYzwVxM7gEjkPLY40qE1QcMayxG

The redirct_url is http not https, I tried to change the parameters redirect_url and redirect_to, but it doesn't work... redirect_url

> facebook_bp = make_facebook_blueprint(scope=['email'])
> 
> @auth.route("/login_with_facebook")
> def login_with_facebook():
>     if not facebook.authorized:
>         return redirect(url_for("facebook.login"))
>     facebook_user = facebook.get('me?fields=id, name, picture.width(512).height(512)').json()

Could you help?

**Comment by singingwolfboy** [comment]
It sounds like your website may be behind a [TLS termination proxy](https://en.wikipedia.org/wiki/TLS_termination_proxy). If that's the case, Flask doesn't know that you're running on HTTPS -- it _thinks_ you're running on insecure HTTP, because the server running your website _is_ running insecure HTTP. Since Flask doesn't know you're using HTTPS, it will generate external links using insecure HTTP -- including the link for the `redirect_uri` parameter.

The solution is to tell Flask about this TLS termination proxy, so it can generate external links correctly. Check out [`werkzeug.contrib.fixers.ProxyFix`](http://werkzeug.pocoo.org/docs/0.14/contrib/fixers/#werkzeug.contrib.fixers.ProxyFix) for a good way to do so. (Note that this is what the documentation recommends for Heroku.)

Does that work?

**Comment by leejoonsung007** [comment]
I check my code again. In my init.py, it has included ProxyFix, but Flask still cannot recognize  HTTP and HTTPS....

code: 

> from flask import Flask
> from flask_sqlalchemy import SQLAlchemy
> from flask_login import LoginManager
> from config import config
> from werkzeug.contrib.fixers import ProxyFix
> from flask_dance.contrib.google import make_google_blueprint
> from flask_dance.contrib.facebook import make_facebook_blueprint
> from raven.contrib.flask import Sentry
> 
> db = SQLAlchemy()
> 
> login_manager = LoginManager()
> login_manager.login_view = 'auth.login'
> 
> 
> def create_app(config_name):
>     app = Flask(__name__)
>     app.config.from_object(config[config_name])
>     config[config_name].init_app(app)
> 
>     db.init_app(app)
> 
>     login_manager.init_app(app)
>   app.wsgi_app = ProxyFix(app.wsgi_app)
>     sentry = Sentry(app)
>     google_bp = make_google_blueprint(scope=['https://www.googleapis.com/auth/userinfo.profile', 'https://www.googleapis.com/auth/userinfo.email'],
>                                       offline=True, reprompt_consent=True,
>                                       redirect_url='https://www.bestchoicehub.com/auth/login_with_google')
> 
>     facebook_bp = make_facebook_blueprint(scope=['email'],
>                                           redirect_url='https://www.bestchoicehub.com/auth/login_with_facebook',
>                                         )
> 
>     from .main import main as main_blueprint
>     app.register_blueprint(main_blueprint)
> 
>     from .auth import auth as auth_blueprint
>     app.register_blueprint(auth_blueprint, url_prefix='/auth')
>     app.register_blueprint(google_bp, url_prefix="/auth")
>     app.register_blueprint(facebook_bp, url_prefix="/auth")
> 
> 
>     return app
>

**Comment by leejoonsung007** [comment]
I check my code again. In my init.py, it has included ProxyFix, but Flask still cannot recognize  HTTP and HTTPS....

code: 

> from flask import Flask
> from flask_sqlalchemy import SQLAlchemy
> from flask_login import LoginManager
> from config import config
> from werkzeug.contrib.fixers import ProxyFix
> from flask_dance.contrib.google import make_google_blueprint
> from flask_dance.contrib.facebook import make_facebook_blueprint
> from raven.contrib.flask import Sentry
> 
> db = SQLAlchemy()
> 
> login_manager = LoginManager()
> login_manager.login_view = 'auth.login'
> 
> 
> def create_app(config_name):
>     app = Flask(__name__)
>     app.config.from_object(config[config_name])
>     config[config_name].init_app(app)
> 
>     db.init_app(app)
> 
>     login_manager.init_app(app)
>   app.wsgi_app = ProxyFix(app.wsgi_app)
>     sentry = Sentry(app)
>     facebook_bp = make_facebook_blueprint(scope=['email'],
>                                           redirect_url='https://www.bestchoicehub.com/auth/login_with_facebook' )
> 
>     from .main import main as main_blueprint
>     app.register_blueprint(main_blueprint)
> 
>     from .auth import auth as auth_blueprint
>     app.register_blueprint(auth_blueprint, url_prefix='/auth')
>     app.register_blueprint(facebook_bp, url_prefix="/auth")
> 
> 
>     return app
>

**Comment by daenney** [comment]
@leejoonsung007 Have you been able to make any progress on this issue? Do you need any further help from us?

**Comment by leejoonsung007** [comment]
Thanks, I have solved this problem by setting the X-Forwarded-$ family of headers.

**Comment by daenney** [comment]
Great! In that case I'll close this issue.
