### ISSUE TITLE
Can't run Azure auth at local machine

### ISSUE THREAD

**Issue by yn-coder** [singingwolfboy/flask-dance#156]
Trying to test the Azure auth on local machine following http://flask-dance.readthedocs.io/en/latest/quickstarts/azure.html

Windows.Live raise the `login.live.com/err.srf?lc=1049#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+`, after login dialog - for any case

1. 127.0.0.1:5000 in app settings 
2. localhost:5000 in app settings 
3. mysite.com:5000 in app settings (set it up in `hosts` file)

In all of cases dns loop is resolved and I can open the url in local browser, and see the login window - when `error redirect url`

For remote heroku it's working well

**Comment by singingwolfboy** [comment]
The error description is "The provided value for the input parameter 'redirect_uri' is not valid." This is an error from the OAuth provider, _not_ from Flask-Dance. You need to set your redirect_uri correctly when configuring your OAuth app on the provider website. Flask-Dance can't help you with this.

**Comment by yn-coder** [comment]
Yes, I know :( But I can't find any diff between redirect_url and my settings.

**Comment by daenney** [comment]
Have you configured those as allowed redirect_uri's in Azure? Just having those in your app settings isn't enough, you need to configure the OAuth client settings in Azure correctly too.

**Comment by yn-coder** [comment]
Of course, I put urls in MS,app settings with carefull, eqactly as it run on local host. Redirect url, client secrek and code - it's configured.

I have two registered app in MS control panel - on epointef to heroku demo (working fine) and second pointed to localhost (login process started, but back request from WL raise the error - `wrong redirect url`)

**Comment by yn-coder** [comment]
Yes, for local app I run with local_app id and secret

**Comment by singingwolfboy** [comment]
Unfortunately, I don't think that we can help you with this problem. As I said earlier, this is an error from your OAuth provider, and it's not something that Flask-Dance can help with. As a result, I'm closing this issue.
