### ISSUE TITLE
Returning a Response object while overriding default behaviour

### ISSUE THREAD

**Issue by Tadaboody** [singingwolfboy/flask-dance#158]
I use `flask-dance` with the `flask-sqlalchemy` backend.
I'd like to return a response object after the `@oauth_authorized.connect` event is fired but also override the default behaviour that will save the token.

The docs say:

>  If you don’t want the token to be stored,
> simply return False from one of your signal receiver functions 

...

> You can also return a Response instance from an event subscriber. If you do, that response will be returned to the user instead of the normal redirect.

Is there a way to do both?

**Comment by singingwolfboy** [comment]
[Here is the relevant code that checks for the return type of the response.](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L257-L263) As you can see, if the return value is a Response instance, then that Response is immediately returned from this function, which means that Flask-Dance will never reach the code that stores the token.

As a result, not only is it _possible_ to do both, but it's _necessary_. Maybe we need to update the documentation to make that more clear. Are you willing to make a pull request to improve the documentation for this?

**Comment by Tadaboody** [comment]
No problem, I'll do my best!
