### ISSUE TITLE
Google, sometimes, requires `redirect_uri` to be `'postmessage'`

### ISSUE THREAD

**Issue by ticosax** [singingwolfboy/flask-dance#159]
https://stackoverflow.com/questions/51106569/what-is-the-purpose-of-postmessage-in-a-redirect-uri
https://developers.google.com/+/sign-in-faq

This is indeed very corner case and a bit shady, but it is actually a thing when the code is obtained by a frontend application which is not managed by flask.

I'm attaching a diff to explain better what I mean.
```diff
diff --git a/flask_dance/consumer/oauth2.py b/flask_dance/consumer/oauth2.py
index 91dd7a4..06d4832 100644
--- a/flask_dance/consumer/oauth2.py
+++ b/flask_dance/consumer/oauth2.py
@@ -232,9 +232,7 @@ class OAuth2ConsumerBlueprint(BaseOAuthConsumerBlueprint):
         self.session._state = state
         del flask.session[state_key]
 
-        self.session.redirect_uri = url_for(
-            ".authorized", next=request.args.get('next'), _external=True,
-        )
+        self.session.redirect_uri = 'postmessage'
 
         log.debug("client_id = %s", self.client_id)
         log.debug("client_secret = %s", self.client_secret)
```

I'd like to know if you were willing to accept a contribution to make this patch a reality. 
It could be triggered by a new parameter given to `make_google_blueprint` called something like like `disable_redirect_uri`

```python
oauth_blueprint = make_google_blueprint(
    client_id=app.config['OAUTH_CLIENT_ID'],
    client_secret=app.config['OAUTH_CLIENT_SECRET'],
    scope=[
        'https://www.googleapis.com/auth/userinfo.email',
        'https://www.googleapis.com/auth/userinfo.profile',
    ],
    offline=True,
    redirect_to='index',
    backend=oauth_backend,
    disable_redirect_uri=True,  # here: new parameter
)
```
Let me know what do you think and I'd be more than happy to make a proper PR.

**Comment by singingwolfboy** [comment]
It appears that this is only for when the OAuth flow is managed by a client-side Javascript application. If that's true, then this option doesn't belong in Flask-Dance, which is only for server-side Python applications. Is there any evidence that this option is designed to be used by server-side apps like the ones Flask-Dance supports?

**Comment by ticosax** [comment]
No, you are right, it is only for hybrid flow involving client-side and server side clients.
