### ISSUE TITLE
Modifying columns set during retrieval of new token

### ISSUE THREAD

**Issue by hammerface** [singingwolfboy/flask-dance#160]
Hi there. I'm using this page as a resource for using google login on my web app:
https://flask-dance.readthedocs.io/en/latest/multi-user.html#overriding-the-default-behavior

Works great until flask dance goes to refresh my token. My problem is related to this passage:

> This example code does not include implementations for the User and OAuth models: you can see that these models are imported from another file. However, notice that the OAuth model has a field called provider_user_id, which is used to store the user ID of the GitHub user. The example code uses that ID to check if we’ve already saved an OAuth token in the database for this GitHub user.

Since provider_user_id is not a default column, when flask dance automatically updates the table after retrieving the new token, it puts nothing into that column and things get ugly. How can I modify that behavior so that this column is also filled when flask dance does its token update?

Not sure if this is the right place to ask this sort of question, but I appreciate any help you can provide.

**Comment by singingwolfboy** [comment]
By default, the automatic token update function simply assigns the token to the `token` property on the `OAuth2ConsumerBlueprint` object: [source code is here](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L168-L169). Assigning to that property will call the backend's `set()` method, [which is here for the SQLAlchemy backend](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/backend/sqla.py#L184-L222). Neither of these pieces of code know anything about updating other fields on the `OAuth` database model.

I believe that you have two options here. You could use the `session_created()` hook to customize the blueprint's session before it is returned, which would allow you to write your own `token_updater()` function that does whatever you want it to do, including saving the user ID or any other data you want. Or, you could write your own database backend that knows how to find and save the user ID when the `set()` method is called. You could even do both, if you want.

Does that give you the information you need?

**Comment by hammerface** [comment]
That helps a lot, I'll give those options a shot. Thanks for you quick help at this hour.

**Comment by singingwolfboy** [comment]
Great! If you manage to get it to work, could you please make a pull request to update the documentation? That way, other people who find themselves in your situation will be able to learn from your experience.

**Comment by hammerface** [comment]
Sure thing, thanks again.
