### ISSUE TITLE
How to override authorization_url parameter?

### ISSUE THREAD

**Issue by mamude** [singingwolfboy/flask-dance#165]
In my application, we need to limit the auth by domain.

How can I change the default:
authorization_url="https://accounts.google.com/o/oauth2/auth"

To:
authorization_url="https://accounts.google.com/o/oauth2/auth?hd=mydomain.com"

Cheers!

**Comment by singingwolfboy** [comment]
There are two options that I can see. The first option is that we can add a new parameter to the `make_google_blueprint()` function to control this. The second option is that you can make your own blueprint using the `OAuth2ConsumerBlueprint` class, and customize it however you want. [Check the file that defines `make_google_blueprint()`: it's pretty straightforward.](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/contrib/google.py)

Can you try using the `OAuth2ConsumerBlueprint` class directly? If that works for you, can you send a pull request to add a new parameter to the `make_google_blueprint()` function?

**Comment by mamude** [comment]
I was able to successfully implement the first option.
Many thanks for the suggestion.
