### ISSUE TITLE
Stale gh-pages branch

### ISSUE THREAD

**Issue by daenney** [singingwolfboy/flask-dance#169]
Looking around the repo during my regular cleanup time I noticed there's a very old gh-pages branch that's still up on https://singingwolfboy.github.io/flask-dance/. There's some broken links in there and other stuff that's not quite up to date.

Should we update that, or perhaps axe it instead in favour of a redirect to https://flask-dance.readthedocs.io/ ?

**Comment by singingwolfboy** [comment]
I think a redirect would be best. Do you know how to do that?

**Comment by daenney** [comment]
The quickest way I can think of is having only an `index.html` with something like this in it:

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Redirecting to https://flask-dance.readthedocs.io</title>
<meta http-equiv="refresh" content="0; URL=https://flask-dance.readthedocs.io/">
<link rel="canonical" href="https://flask-dance.readthedocs.io/">
</head>
</html>
```

**Comment by daenney** [comment]
The other way would be using JS as for some reason people recommend against the `<meta refresh>` method, though I've personally never had anything go wrong with it.

**Comment by singingwolfboy** [comment]
I just updated the `index.html` file as you suggested, and the redirect seems to work. Thanks!
