### ISSUE TITLE
provider_user_id isn't written to OAuth table

### ISSUE THREAD

**Issue by CyberCube37** [singingwolfboy/flask-dance#175]
When running the example code for user creation with flask-dance I ran into a problem, the provider_user_id isn't written to OAuth table. I checked this multiple times but it's the same every time. I printed the variable provider_user_id right before the new user creation and it's not null but when I check the table it says null. (I left out other code, everything else works besides this). If you need any other info I'll be happy to provide it. 

```python
def logged_in(blueprint, token):
    if not token:
        flash("Failed to log in with GitHub.", category="error")
        return False

    resp = blueprint.session.get("/user")
    if not resp.ok:
        msg = "Failed to fetch user info from GitHub."
        flash(msg, category="error")
        return False

    github_info = resp.json()
    github_user_id = str(github_info["id"])

    # Find this OAuth token in the database, or create it
    query = OAuth.query.filter_by(
        provider=blueprint.name,
        provider_user_id=github_user_id,
    )
    try:
        oauth = query.one()
    except NoResultFound:
    print(github_user_id)
    print(query)
        oauth = OAuth(
            provider=blueprint.name,
            provider_user_id=github_user_id,
            token=token,
        )
    print(github_user_id, type(github_user_id))

    if oauth.user:
        # If this OAuth token already has an associated local account,
        # log in that local user account.
        # Note that if we just created this OAuth token, then it can't
        # have an associated local account yet.
        login_user(oauth.user)
        flash("Successfully signed in with GitHub.")

    else:
        # If this OAuth token doesn't have an associated local account,
        # create a new local user account for this user. We can log
        # in that account as well, while we're at it.
        user = User(
            # Remember that `email` can be None, if the user declines
            # to publish their email address on GitHub!
            email=github_info["email"],
            name=github_info["name"],
        )
        # Associate the new local user account with the OAuth token
        oauth.user = user
        # Save and commit our database models
        db.session.add_all([user, oauth])
        db.session.commit()
        # Log in the new local user account
        login_user(user)
        flash("Successfully signed in with GitHub.")

    # Since we're manually creating the OAuth model in the database,
    # we should return False so that Flask-Dance knows that
    # it doesn't have to do it. If we don't return False, the OAuth token
    # could be saved twice, or Flask-Dance could throw an error when
    # trying to incorrectly save it for us.
    return False


```
<img width="156" alt="screenshot 2018-10-01 at 18 35 40" src="https://user-images.githubusercontent.com/35262980/46302575-aac54500-c5a9-11e8-805e-2eb262f96c3b.png">
<img width="156" alt="screenshot 2018-10-01 at 18 35 54" src="https://user-images.githubusercontent.com/35262980/46302573-aac54500-c5a9-11e8-8e63-670bdfe5fad0.png">
EDIT: after some more research I found out that it does get written to the table and the value is there right after it gets written, but when oauth redirects you to your redirect URI the value just dissapears and is suddenly NULL. Can you help please?

**Comment by singingwolfboy** [comment]
Unfortunately, I don't know what the problem is. Is some other code in your project writing to that database table? Are you sure the transaction is completing successfully?

**Comment by CyberCube37** [comment]
I will provide the code and do some more tests and I will have my friend run it to see if it's just on my computer just in case

**Comment by singingwolfboy** [comment]
Any news on this, @CyberCube37? It seems like you're the only person having this problem, so I expect that the problem is with your project, not with the Flask-Dance library.

**Comment by singingwolfboy** [comment]
Since I haven't heard anything further, I'm assuming that this issue can be closed.
