### ISSUE TITLE
Issues using the example program for Azure AD

### ISSUE THREAD

**Issue by gauravdce** [singingwolfboy/flask-dance#180]
**AADSTS50194: Application 'xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx' is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.**'''

This is the error received after testing the Azure program

**Comment by singingwolfboy** [comment]
@steven-martins, you're the maintainer for the Azure configuration. Do you know anything about this?

**Comment by atwalsh** [comment]
Related issue: https://github.com/MicrosoftDocs/azure-docs/issues/19346

**Comment by daenney** [comment]
The upstream issue has been closed and it's suggested this is a user error, i.e the application isn't registered as a multi-tenant application while the common endpoints are used. This is something that should be fixed on the Azure side and should be a simple settings change in the Azure control panel.

The documentation in question we had for the Azure quickstart is gone so there isn't much to fix on our side about this anymore. Example apps have been split out into singingwolfboy/flask-dance-$provider repositories. If someone wishes to contribute one from Azure I'm sure @singingwolfboy would be happy to take it.

For now I'm going to close this issue.

**Comment by alfredoniw220** [comment]
AADSTS50194: Application  is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.


Saludos tengo el mismo conflicto alguien tendrá alguna respuesta ? agradecido
