### ISSUE TITLE
how to use google services

### ISSUE THREAD

**Issue by louking** [singingwolfboy/flask-dance#182]
I am trying to map https://developers.google.com/drive/api/v3/quickstart/python, in particular the line `service = build('drive', 'v3', http=creds.authorize(Http()))` through use of flask-dance.

I see at https://flask-dance.readthedocs.io/en/latest/providers.html#module-flask_dance.contrib.google `flask_dance.contrib.google.google` that this is a `requests.Session` that has the google authentication token loaded.

But not sure how to use that with the `build()` method in the example. https://googleapis.github.io/google-api-python-client/docs/epy/googleapiclient.discovery-module.html#build indicates the http parameter is An instance of httplib2.Http or something that acts like it that HTTP requests will be made through.

I tried using the `requests.Session` object as the http parameter (on the off chance it would work), but got some error in the `build()` process.

Note: I'm using SQLAlchemy for storage.

Any suggestions, examples?

**Comment by singingwolfboy** [comment]
@louking: can you tell me about your use-case here? _Why_ do you want to integrate these two libraries? Maybe there's a better way to do what you're trying to do.

**Comment by louking** [comment]
Maybe it was because I wanted to pick up flask-security and it looked like flask-dance was already integrated with that. I just assumed I would be able to use it with the google apis.

**Comment by louking** [comment]
I guess I'll stop trying to integrate with flask-dance and use my wrapper instead.

**Comment by singingwolfboy** [comment]
> Maybe it was because I wanted to pick up flask-security and it looked like flask-dance was already integrated with that. I just assumed I would be able to use it with the google apis.

You absolutely _can_ use Flask-Dance with the Google APIs -- that's what it's explicitly designed for! However, there's a difference between an API and an "API client library". An API client library is designed to make it easier to use an API in one specific way, such as by exposing objects and methods and abstracting away the actual API calls.

What I'm saying is that, while you can use Flask-Dance to call the Google APIs directly, you _cannot_ use Flask-Dance to integrate with the Google API client libraries. (Or at least, if it's possible, it's definitely not supported, and I can't answer questions or help you with your problems related to this.)
