### ISSUE TITLE
Tokens expiring but `authorized` still passing

### ISSUE THREAD

**Issue by JellyWX** [singingwolfboy/flask-dance#186]
Code is present at https://github.com/reminder-bot/web

Users are having issues that the token is expired yet the cache is not cleared. Is this a browser issue or an issue that the cache is set to live too long? These issues have only recently begun.

Using `contrib.discord` with Flask Python 3.6. Not aware of any changes to the Discord OAuth API. Increasingly confused since this issue is difficult to reproduce but definitely happening

`Nov 20 07:38:48 fusiondiscordbots.com gunicorn3[1126]: oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (toke`

**Comment by daenney** [comment]
That seems to be a cache issue on whomever is caching it. You can see the `TokenExpiredError` getting raised by Flask-Dance through requests-oauthlib, so Flask-Dance has caught onto the fact that the token is expired.

I'd be happy to try and help but I'd need a bit more than "here is a code dump to sift through" and a half broken stack trace.

**Comment by JellyWX** [comment]
Okay, thanks. I've done some error catching which seems to work, but I don't have any analytics on the browsers people were using etc. when errors did occur, so there's not much I can feed back into this now, sorry
