### ISSUE TITLE
authorized_url is http, not https:

### ISSUE THREAD

**Issue by aardvark82** [singingwolfboy/flask-dance#188]
I'm calling flask-dance with make_slack_blueprint, and the URL flask-dance sends to Slack as the authorized_url is 

"http://mydomain.com/login/slack/authorized"

instead of the proper

"http**s**://mydomain.com/login/slack/authorized"

This means the call fails on my production server since I did not set the insecure HTTPS env variable there (and shouldn't)

how do I get flask dance to pass the https URL for the authorized_url? If I try to specify an absolute path as the authorized url then it gets treated as a relative path.

    blueprint_slack = make_slack_blueprint(
        client_id="sdfdsg242894452",
        client_secret="53019238021358rrgdf",
        scope=["identify",  "chat:write:bot"],
        **authorized_url='https://www.mydomain.com/login/slack/authorized',**   
        redirect_url='/slack_authorized',
)

If it is meaningful:

I'm running Flask 1.0+ 
- with Flask-talisman 0 all URl's redirect to https:// and I have HSTS set 
- with a gunicorn server, with relevant https flags set in my gunicorn config file

secure_proxy_ssl_header = ('HTTP_X_FORWARDED_PROTO', 'https')
forwarded_allow_ips = '*'
secure_scheme_headers = {'X-Forwarded-Proto': 'https'}
x_forwarded_for_header = 'X-FORWARDED-FOR'

PS: And yes, the client_id and secret above are bogus!

**Comment by Lexy2** [comment]
Why do you specify the `redirect_url` explicitly?
Flask-Dance generates `/login/slack` and `/login/slack/authorized` views automatically, you don't have to specify them. The `redirect_url` is something your app will show after the user has clicked 'Add to Slack' button and all the OAuth dance has completed.
OAuth2ConsumerBlueprint does not use http scheme, it just adds the url rule relative to the root of your WSGI app. So if your app runs in WSGI env of http://mydomain.com, the BP will also generate http://mydomain.com/slack/authorized URL for authorized_url.

You should do something like:
```
blueprint_slack = make_slack_blueprint(
    client_id="sdfdsg242894452",
    client_secret="53019238021358rrgdf",
    scope=["identify",  "chat:write:bot"],
    redirect_to="authed_handler")
app = Flask(__name__)
app.register_blueprint(blueprint_slack, url_prefix="/login")

@app.route("/slack_authorized")
def authed_handler():
    return "Authorized successfully!"
```
and then when you go to 
https://mydomain.com/login/slack
The app will redirect you with 302 Found to api.slack.com, which will redirect you back to https://mydomain.com/login/slack/authorized, which will then show the user https://mydomain.com/slack_authorized

**Comment by aardvark82** [comment]
Thanks for your response - I should have mentioned the code above was my attempt at fixing the problem - my original code was using the default route:

    blueprint_slack = make_slack_blueprint(
        client_id="blablabla",
        client_secret="blablabla",
        scope=["identify"],
        redirect_url='/slack_authorized',
    )

Which leads to the redirect to http://mydomain.com/login/slack/authorized

The website and calls are all hosted on https:// which is why I mentioned the gunicorn config.

How do I check / set the root of my WSGI app?

**Comment by aardvark82** [comment]
FYI the code above is called in a setup() method  that is called before_first_request - what's the best place to specify? Can't / don't want to put it inline as I like to keep all init code clean.

@app.before_first_request
def setup():
             setupSlack()  # code above

**Comment by aardvark82** [comment]
And to be comprehensive, Flask-Dance login & auth work on my dev server with the insecure HTTPS env variable set so my routes & flow seem to be properly setup. The issue is the default handler uses the http:// base instead of https:// on the production server.

**Comment by Lexy2** [comment]
Well, then it might be the issue with gunicorn. Also, check your Slack app redirect URLs.

**Comment by Lexy2** [comment]
> ```
>  redirect_url='/slack_authorized',
> )
> ```
> 
> Which leads to the redirect to http://mydomain.com/login/slack/authorized

Hmm, this redirect_url should redirect to http://mydomain.com/slack_authorized, exactly as you specified.

**Comment by Lexy2** [comment]
> Is there a way to fully overload the redirect_url with an absolute path and not a relative one?

Yes, if you specify the URL with the protocol, https://mydomain.com, it will redirect to absolute path.
Not sure how it works with talisman though

**Comment by aardvark82** [comment]
Yes, https URL's are specified - , although http URL's can be specified too as valid redirect URL's for local testing.

**Comment by iw-an** [comment]
For anyone else coming across this issue who might be using heroku + cloudflare encountering this issue. Your issue may lay within your Cloudflare settings. SSL mode needs to be set to full so that Cloudflare will forward the request correctly. Without heroku will only see `X-Forwarded-Proto: http`

**Comment by Lexy2** [comment]
@aardvark82,

Digging deeper, I found out that this situation is well-known and mentioned in [Flask documentation](http://flask.pocoo.org/docs/1.0/deploying/wsgi-standalone/#proxy-setups).

Thus, instead of implementing a custom reverse proxy handler, you could use a nicer code of
```
from werkzeug.contrib.fixers import ProxyFix

app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)
```

**Comment by daenney** [comment]
There's a few things here:

- If you want HTTPS, ensure the request comes in over HTTPS
- If/when you proxy the request to a backend, ensure you set `X-Forwarded-Proto` to `https` and also ensure you set/proxy `X-Forwarded-For` to preserve the request origin

That should be enough for Flask to do the right thing, no need for the `ProxyFix` at that point. The sample nginx configuration given in Flask's config is what you need.

For Apache there's also [mod_remoteip](https://httpd.apache.org/docs/trunk/mod/mod_remoteip.html) nowadays, to be paired with a setting of `RemoteIPHeader X-Forwarded-For`.

**Comment by daenney** [comment]
There's also documentation on our side: https://flask-dance.readthedocs.io/en/latest/proxies.html
