### ISSUE TITLE
Using Flask-dance for Slack app directory installation or with Add To Slack button

### ISSUE THREAD

**Issue by Lexy2** [singingwolfboy/flask-dance#191]
Hi @singingwolfboy!
Thank you for the great Flask app to manage OAuth dance.

I use Flask-Dance to manage Slack authentication and ran into an issue where your experience may be beneficial.
If you build OAuth dance starting from `/login/slack` view, everything works fine. However, if you try to install the app from _Add to Slack_ button or directly from Slack app directory, it forwards you to 
`https://slack.com/oauth/authorize?scope=SCOPE&client_id=CLIENT_ID`, and once you authorize the app, Slack redirects you to a `redirect_url` that I set in my Slack app to `login/slack/authorized`.
Slack sending the request to `login/slack/authorized` does not set the state as the OAuth dance is not initiated from the consumer.
Here comes the problem. As per `flask_dance/consumer/oauth2.py`, lines 225-228:
```
        if state_key not in flask.session:
            # can't validate state, so redirect back to login view
            log.info("state not found, redirecting user to login")
            return redirect(url_for(".login"))
```
So, Flask-Dance does not see the state parameter recorded in the current session and asks Slack to authorize the app for the second time, now sending the request with `state` parameter set, and the user has to click _Authorize_ twice.

It's probably not a problem of Flask-Dance per se, but I would not like to implement a separate Slack redirect URL just for this install flow.

What do you think, how can work around this problem? Or maybe you could suggest a pull request to Flask-Dance?

Thanks!

**Comment by Lexy2** [comment]
Found https://github.com/singingwolfboy/flask-dance/pull/36, reading https://github.com/singingwolfboy/flask-dance/issues/34 related to it.

**Comment by singingwolfboy** [comment]
I'm not sure how to solve this problem without weakening the security that the `state` token provides. Any suggestions?

**Comment by Lexy2** [comment]
Well, there is no easy answer to this. All variants weaken security but they improve user experience.
Maybe add an option for providers that allow such scenarios, like an `ignore_state_absence: bool` parameter to `make_slack_blueprint` function and respective handling in the `OAuth2ConsumerBlueprint` class?
Or, require presence of the `state` parameter only if the flow was started from the `/login/<provider>` view?
Or, if the flow was started from `/login/<provider>` view, pass the `redirect_uri` parameter that requires the state, and your default provider's callback URI does not?

**Comment by daenney** [comment]
I don't like the idea of the boolean option at all. That risks severely weakening the security for everyone without anyone really noticing and I'd similarly prefer to avoid trying to deduce what to do based on where a flow was started from.

I think the idea with having separate callback URLs might be workable. I'd prefer to have the defaults stay as they are but we could consider introducing a `/weak` route for this purpose that could be set as the redirect URI in the Slack app?

**Comment by Lexy2** [comment]
I'd vote for this route. Otherwise, I'd have to implement weak OAuth flow myself, which kinda diminishes the value of using Flask-Dance.

**Comment by remyabel** [comment]
The [Slack docs](https://api.slack.com/docs/oauth) refers to an optional `state` value:

> - `state` - unique string to be passed back upon completion (optional)
> The `state` parameter should be used to avoid forgery attacks by passing in a value that's unique to the user you're authenticating and checking it when auth completes.

Then it says:

> If the user authorizes your app, Slack will redirect back to your specified `redirect_uri` with a temporary code in a `code` GET parameter, as well as a `state` parameter if you provided one in the previous step

Can this somehow be utilized?

**Comment by Lexy2** [comment]
Fixing this saves one click for development applications.

Production applications (published to Slack app directory) can have a [direct install URL](https://api.slack.com/slack-apps#direct_install) that facilitates installation without compromising the security.

In this case, there is no need to implement a weaker route in Flask-Dance at all. I will set the direct install URL to `<host URI>/login/slack` - and the app directory will get the state parameter as required by the RFC.

Thank you for your time and patience.

Regards, Lexy
