### ISSUE TITLE
Twitter bp isn't reading config correctly from app config

### ISSUE THREAD

**Issue by Tadaboody** [singingwolfboy/flask-dance#197]
This should be tested by https://github.com/singingwolfboy/flask-dance/blob/master
/tests/contrib/test_twitter.py#L28 
but adding 
```py    
    twitter_bp = make_twitter_blueprint(redirect_to="index")
    assert twitter_bp.client_key == "foo"
    assert twitter_bp.client_secret == "bar"
    app.register_blueprint(twitter_bp)
```
fails the test.

**Comment by Tadaboody** [comment]
I'll add a PR adding failing lines for more clarity

**Comment by Tadaboody** [comment]
This is a problem because I end up calling `twitter_bp.get()` with an existing token but without the client key loaded from the configuration. because it is loaded in `bp.before_request` which wasn't yet called

**Comment by singingwolfboy** [comment]
Can you explain why you're trying to use the blueprint's session object *outside* of an HTTP request? It's not designed to be used that way.
