### ISSUE TITLE
Redirecting to a dynamic URL in Google blueprint

### ISSUE THREAD

**Issue by mephi42** [singingwolfboy/flask-dance#203]
I would like to implement the following scenario with Flask-Dance: when a not logged in user tries to access a protected page, he is given an option to log in via Google and, having succeeded, return to the protected page. Having browsed the Flask-Dance code, I've constructed the following URL:

```
https://$HOST/login/google?next=https://$HOST/whatever/user/was/trying/to/do/in/the/first/place
```

However, this fails on the Google side with

```
The redirect URI in the request, ..., does not match the ones authorized for the OAuth client
```

because Google supports only statically configured redirect URIs. I have read that one should use `state` parameter in this case. Does Flask-Dance support that out of the box?

**Comment by daenney** [comment]
I would suggest avoiding messing with the state parameter. I can't remember that ever being recommended and it's integral to the OAuth dance itself.

Instead, you can do something like this:

```python
if google.authorized
  next_url = session.pop("next_url", url_for("app.index")
  return redirect(next_url)
```

At the point where you trigger the Oauth dance you `session["next_url"] = "wherever you wanna go"`

**Comment by mephi42** [comment]
Thanks! The following appears to have worked:

```patch
--- consumer/oauth2.py.orig	2019-01-06 13:41:40.000000000 +0300
+++ consumer/oauth2.py	2019-01-06 13:51:32.851410052 +0300
@@ -42,6 +42,7 @@
             redirect_to=None,
             session_class=None,
             backend=None,
+            store_next_url_in_session=False,
 
             **kwargs):
         """
@@ -134,6 +135,8 @@
         self.redirect_url = redirect_url
         self.redirect_to = redirect_to
 
+        self.store_next_url_in_session = store_next_url_in_session
+
         self.teardown_app_request(self.teardown_session)
 
     @property
@@ -178,8 +181,13 @@
 
     def login(self):
         log.debug("client_id = %s", self.client_id)
+        next_url = request.args.get("next")
+        if next_url and self.store_next_url_in_session:
+            state_next_url_key = "{bp.name}_oauth_next_url".format(bp=self)
+            flask.session[state_next_url_key] = next_url
+            next_url = None
         self.session.redirect_uri = url_for(
-            ".authorized", next=request.args.get('next'), _external=True,
+            ".authorized", next=next_url, _external=True,
         )
         url, state = self.session.authorization_url(
             self.authorization_url, state=self.state,
@@ -191,20 +199,26 @@
         log.debug("redirect URL = %s", url)
         return redirect(url)
 
+    def get_next_url(self):
+        if self.store_next_url_in_session:
+            state_next_url_key = "{bp.name}_oauth_next_url".format(bp=self)
+            if state_next_url_key in flask.session:
+                return flask.session.pop(state_next_url_key)
+        if "next" in request.args:
+            return request.args["next"]
+        if self.redirect_url:
+            return self.redirect_url
+        if self.redirect_to:
+            return url_for(self.redirect_to)
+        return "/"
+
     def authorized(self):
         """
         This is the route/function that the user will be redirected to by
         the provider (e.g. Twitter) after the user has logged into the
         provider's website and authorized your app to access their account.
         """
-        if "next" in request.args:
-            next_url = request.args["next"]
-        elif self.redirect_url:
-            next_url = self.redirect_url
-        elif self.redirect_to:
-            next_url = url_for(self.redirect_to)
-        else:
-            next_url = "/"
+        next_url = self.get_next_url()
         log.debug("next_url = %s", next_url)
 
         # check for error in request args
--- contrib/google.py.orig	2018-12-26 20:21:43.000000000 +0300
+++ contrib/google.py	2019-01-06 13:43:32.164129579 +0300
@@ -113,6 +113,7 @@
         authorization_url_params=authorization_url_params,
         session_class=session_class,
         backend=backend,
+        store_next_url_in_session=True,
     )
     google_bp.from_config["client_id"] = "GOOGLE_OAUTH_CLIENT_ID"
     google_bp.from_config["client_secret"] = "GOOGLE_OAUTH_CLIENT_SECRET"
```

Would it make sense to add this in some form to Flask-Dance?

**Comment by daenney** [comment]
I think that might be useful to add. What do you think, @singingwolfboy? A generic mechanism for this purpose that works across providers seems useful, though I wonder if I've missed something and we already have that capability somewhere?

**Comment by singingwolfboy** [comment]
I wrote the logic for `request.args["next"]` because I figured it would be useful at some point, but I admit that I've never actually used it, or even tested it with a real OAuth provider. If OAuth providers don't allow for arbitrary URL parameters in the authorized redirect URI, I can see that being a problem.

On the other hand, I also recently learned about [open redirect vulnerablities](https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet), which is a security vulnerability where the attacker can use an unvalidated redirect for phishing. If OAuth providers don't allow for arbitrary URL parameters in the authorized redirect URI, that mitigates the vulnerability (although it's still annoying for the developer).

To be honest, I don't like the idea of building *another* redirect facility into Flask-Dance -- and maybe the `request.args["next"]` redirection should be removed, since it apparently doesn't work the way I expected. Instead, the application developer could implement post-authorization redirects in the following way:

1. Before the OAuth dance begins, the "next" URL for the user is stored somewhere; either in the `flask.session` object, or in a database.
2. The user is redirected to the `login` view for the Flask-Dance blueprint, which kicks off the OAuth dance.
3. The application developer hooks into the [`oauth_authorized` signal](https://flask-dance.readthedocs.io/en/latest/signals.html#flask_dance.consumer.oauth_authorized), looks up the "next" URL from the `flask.session` object or the database, and return a redirect from the signal handler. Because a redirect is a kind of [Response](http://flask.pocoo.org/docs/api/#flask.Response), the `authorized` view will return the redirect to the user.

Maybe we need to make this clearer in the documentation?

**Comment by daenney** [comment]
Ya, we should start with cleaning up the docs around this.

I'd like to have this as a generic mechanism if possible though as I can see it being useful to many but also slightly error prone to do correctly. If we can take that burden away I think that would be a net bonus. Afaik it's always safe to store things in the session and the app can configure whether session is baked by a cookie, a database or something else if I recall correctly?

**Comment by daenney** [comment]
We now have documentation on how to handle custom/dynamic redirects: https://flask-dance.readthedocs.io/en/latest/understanding-the-magic.html#finishing-the-dance.

Though I would like to have a generic mechanism to handle this, there are valid concerns around Flask-Dance not doing any magic for you. Different applications might have different needs based on what providers support (using a cookie vs. a request arg vs. a header vs something else entirely) and what level of security they desire.

I'm not fond of the approach of having one method that just tries a whole bunch of different options and picks the first one that happens to work. Aside from the fact that we somehow have to prioritise the options it will try, we have no way of knowing if the option we pick is what the developer intended. As such it's safer if people implement the redirect handling themselves and explicitly make the choice on how to do this.

If someone can come up with a PR that implements this facility in a fashion that works across all providers while ensuring the developer remains in full control of the redirect behaviour I would be happy to review that.

In the mean time, I'm closing this issue.

**Comment by cancan101** [comment]
Maybe I am reading this wrong. but it seems if a redirect is returned from the signal the token is never set:
https://github.com/singingwolfboy/flask-dance/blob/1500b7bd6d34dd2fb79b87f53112d70642f5cf02/flask_dance/consumer/oauth2.py#L271-L285

**Comment by singingwolfboy** [comment]
@cancan101 True! The expectation is that if you return a redirect, you _also_ need to save the token yourself -- but the documentation does not make that clear. Can you make a pull request to the docs (in the `docs` folder of the repo) to make that clearer? 😄

**Comment by cancan101** [comment]
I can up date the docs... but why push that responsibility on the user? Seems  like there is a non trivial amount of logic in setting the token (ie handling errors) that I would guess most consumers would still want to use.

I think in the base case of just wanting to customize redirects (ie to send the user back to the where they originally came from) where the logic is:
```
    next_url = flask.session["next_url"]
    return flask.redirect(next_url)
```
having to also set the token seems unnatural.

**Comment by daenney** [comment]
Lets discuss this in a separate issue. It's unrelated to the original issue.
