### ISSUE TITLE
Hubspot Custom Blueprint "MissingTokenError"

### ISSUE THREAD

**Issue by jcopacetic** [singingwolfboy/flask-dance#211]
I'm following this example: https://flask-dance.readthedocs.io/en/latest/quickstarts/sqla-multiuser.html

but instead of github I am creating a custom blueprint to connect to Hubspot.

Hubspot sends the token through the url as '?code=<token>". I am seeing this in the url where I am getting the error. it occurs to me that flask_dance doesn't know to look at the 'code' query in the url for the token. I would be very grateful if someone could direct me on how to fix this. 

```
from flask_dance.consumer.backend.sqla import OAuthConsumerMixin, SQLAlchemyBackend
from flask_dance.consumer import OAuth2ConsumerBlueprint, oauth_authorized, oauth_error

blueprint = OAuth2ConsumerBlueprint(
  "hubspot", __name__,
  client_id="_not_for_you_",
  client_secret="_not_for_you_",
  token_url="https://api.hubapi.com/oauth/v1/token",
  redirect_uri='https://127.0.0.1:5000',
  scope=["contacts"],
  authorization_url='https://app.hubspot.com/oauth/authorize',
)
app.register_blueprint(blueprint, url_prefix="/login")

#create/Login Local user on Succesful OAuth Login
@oauth_authorized.connect_via(blueprint)
def hubspot_logged_in(blueprint, token):
  if not token:
      flash("Failed to log in with Hubspot.", category="error")
      return False

  resp = blueprint.session.get("/user")
  if not resp.ok:
      msg = "Failed to fetch user info from Hubpost."
      flash(msg, category="error")
      return False

  hubspot_info = resp.json()
  hubspot_user_id = str(github_info["id"])

  # Find this OAuth token in the database, or create it
  query = OAuth.query.filter_by(
    provider=blueprint.name,
    provider_user_id=hubspot_user_id,
  )
  try:
    oauth = query.one()
  except NoResultFound:
    oauth = Oauth(
      provider=blueprint.name,
      provider_user_id=hubspot_user_id,
      token=token,
    )

  if oauth.user:
    login_user(oauth.user)
    flash("Successfully signed in with Hubspot.")
  else:
    # Create a new local user account for this user
    user = User(
      # Remember that 'email' can be None, if the user declines
      email=Hubspot_info["email"],
      name=hubspot_info["name"],
    )
    oauth.user = user
    db.session.add_all([user, oauth])
    db.session.commit()
    login_user(user)
    flash("Successfully signed in with hubspot")
  
  #Disable Flask-Dance's default behavior for saving the OAuth token
  return False
```

**Comment by singingwolfboy** [comment]
[Here is the `authorized` view](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L194) that handles exchanging the authorization code for an access token. The [actual work in that function](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L242-L247) is delegated to the [requests-oauthlib](https://github.com/requests/requests-oauthlib) library, and it should be able to [parse the `code` query arg out of the request URL](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L206-L209).

Is there something more unusual going on? Also, once you get this working, would you be willing to contribute a configuration for Hubspot, so others can use it easily as well?

**Comment by singingwolfboy** [comment]
You may also find this example project useful as a starting point: https://github.com/singingwolfboy/flask-dance-twitter-multi

**Comment by jcopacetic** [comment]
@singingwolfboy sorry for the delay, I am a novice in python/flask and completely new to oauth so I have been running around all over the internet trying to find something that will connect and forgot to check in. 

I can get authorization in postman, no problem. for some reason the only way I can get the access token and refresh token is using simple request methods. Flask_Dance, Flask_OAuthlib, and others I have tried can't find the token. I wish I could find a Hubspot specific python OAuth2 tutorial, there needs to be one,  and would be happy to make one as well as contribute, provided Flask_Dance is the one I get figured out. Here's the quickstart Hubspot OAuth tutorial if you want to check it out: https://developers.hubspot.com/docs/methods/oauth2/oauth2-quickstart

I will give flask dance another go send an update if I get it. Thanks for the replies.

**Comment by singingwolfboy** [comment]
I'm closing this issue due to a lack of updates.

**Comment by fabrice102** [comment]
I had a similar error, that I fixed by adding `include_client_id=True` Here is my working example:

```python
from requests_oauthlib import OAuth2Session

client_id = ''
client_secret = ''
redirect_uri = 'https://127.0.0.1'
authorization_base_url = 'https://app.hubspot.com/oauth/authorize'
token_url = 'https://api.hubapi.com/oauth/v1/token'
scope = ["forms"]

oauth = OAuth2Session(client_id=client_id, redirect_uri=redirect_uri, scope=scope)
authorization_url, state = oauth.authorization_url(authorization_base_url)
print('Please go to %s and authorize access.' % authorization_url)
authorization_response = input('Enter the full callback URL')

token = oauth.fetch_token(token_url=token_url,
                          authorization_response=authorization_response,
                          client_id=client_id,
                          client_secret=client_secret,
                          include_client_id=True)
```

**Comment by pafuent** [comment]
In my case, I fixed the issue filling the **token_url_params** parameter with a dictionary with the **include_client_id** key
Here is the fix on @jcopacetic example 
```python
blueprint = OAuth2ConsumerBlueprint(
  "hubspot", __name__,
  client_id="_not_for_you_",
  client_secret="_not_for_you_",
  token_url="https://api.hubapi.com/oauth/v1/token",
  redirect_uri='https://127.0.0.1:5000',
  scope=["contacts"],
  authorization_url='https://app.hubspot.com/oauth/authorize',
  token_url_params={'include_client_id': True},
)
```

Hope this helps the next one that finds this issue (it helped me to came up with this fix :wink:)
