### ISSUE TITLE
@<contrib>.authorization_required - does not work (example or production code)

### ISSUE THREAD

**Issue by bkgoodman** [singingwolfboy/flask-dance#213]
I've been banging my head against a wall with a _similar_ issue in my code - so I though I'd try a sample to sanity check. It turns out - the sample doesn't work - and it's the same _line_ that has the problem as my code (though in slightly different way):

When running the code in your README/quickstart - on launch - I get:

`RuntimeError: Working outside of application context.`

In your code:

```python
@app.route("/")
@github.authorization_required
def index():
    resp = github.get("/user")
```

If I remove the `@github.authorization_required` - this error goes away.

I am of course concerned bycause in my code (using the google backend), when I do:

```python
@app.route('/test/oauth')
@google.authorization_required
def TestStd():
    return "Google auth Required"
```

I get:

`AttributeError: 'AppContext' object has no attribute 'google_oauth'`

Which appears to be related to the following:

```python
    @google_bp.before_app_request
    def set_applocal_session():
        ctx = stack.top
        ctx.google_oauth = google_bp.session

    return google_bp

google = LocalProxy(partial(_lookup_app_object, "google_oauth"))
```

from contrib/google.py

(which I can't really make heads-or-tails out of).

Are these two issues related? How can I resolve?

Thanks!

-BKG

**Comment by daenney** [comment]
I'm going to consider this one fixed since the erroneous example has been corrected. If you're still experiencing issues after following the updated documentation feel free to re-open this issue.
