### ISSUE TITLE
`include_client_id` in requests oauthlib 1.2.0 is not clear

### ISSUE THREAD

**Issue by AdamGold** [singingwolfboy/flask-dance#218]
Migrating from `requests-oauthlib` 1.0.0 to 1.2.0, Instagram stopped working.
After some debugging, I found out that the `client_id` and `client_secret` are not being sent. Long story short, I've added `token_url_params={'include_client_id': True}` to the initiation of the Instagram blueprint.
I think it should be more clear how to use the `include_client_id` parameter, and pass it as a standalone param instead of inside a dict.

**Comment by singingwolfboy** [comment]
As mentioned in the pull request:

> Most people using Flask-Dance shouldn't have to think about requests-oauthlib, or whether it's correct to include the client ID, or any of those fiddly OAuth details. The whole point of Flask-Dance is to make it simpler. `token_url_params` provides an opportunity for developers who know those fiddly details to configure them as necessary, but including this option in the top-level arguments (and adding documentation for that option) seems needlessly confusing to me.
