### ISSUE TITLE
detect https not the right way

### ISSUE THREAD

**Issue by lepture** [singingwolfboy/flask-dance#22]
I've just scanned the code, and found

```python
if request.headers.get("X-Forwarded-Proto", "http") == "https":
    url = url.with_scheme("https")
```

It is not the right way. Application code should not take care of such thing, it should always read from `wsgi.url_scheme`.

`wsgi.url_scheme` can be rewrite by gunicorn/uwsgi etc.

For gunicorn: http://docs.gunicorn.org/en/0.16.0/configure.html#secure-scheme-headers

For uwsgi: http://uwsgi-docs.readthedocs.org/en/latest/Vars.html#uwsgi-scheme

**Comment by singingwolfboy** [comment]
@lepture Can you provide a pull request? I'm not sure where this `wsgi` object comes from, or how to use the value of `wsgi.url_scheme`. Can you also provide an example of where the current code is a problem?

**Comment by lepture** [comment]
@singingwolfboy 

```python
if request.is_secure:
     do_something
```

**Comment by singingwolfboy** [comment]
@lepture yes, [the code is already doing that](https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/oauth2.py#L160).

**Comment by singingwolfboy** [comment]
Sounds like this issue is resolved.
