### ISSUE TITLE
Rename "backend" to "storage"

### ISSUE THREAD

**Issue by singingwolfboy** [singingwolfboy/flask-dance#223]
I think I made a mistake when picking the name "backend" for the part of Flask-Dance that stores and retrieves OAuth tokens. "Backend" and "frontend" already have pretty well agreed-upon meanings in the context of web development, so talking about a different kind of "backend" is kind of weird.

Since the purpose of this object is to store and retrieve data, I think it should be called a "storage" instead of a "backend". I've already updated the docs in #221 to account for this change. We will need to update the code, as well.

Note that this will *definitely* be a backwards-incompatible change, which means we'll need to release it with Flask-Dance 2.0.

**Comment by mrsaicharan1** [comment]
@singingwolfboy I'm trying to implement Twitter authentication and flask_dance throws out an error saying that 
`AssertionError: A name collision occurred between blueprints <flask_dance.consumer.oauth1.OAuth1ConsumerBlueprint object at 0x7f29b2ab1860> and <flask_dance.consumer.oauth1.OAuth1ConsumerBlueprint object at 0x7f29b3418198>. Both share the same name "twitter". Blueprints that are created on the fly need unique names.
` . For further reference , here's the link to my PR to the repo. https://github.com/fossasia/open-event-server/pull/5600

**Comment by daenney** [comment]
Please open a separate issue. This doesn't seem to have anything to do with the proposal to change some of the internals of flask-dance.

**Comment by mrsaicharan1** [comment]
Will do it.

**Comment by mrsaicharan1** [comment]
@daenney Created it. Please check :)
