### ISSUE TITLE
Double Blueprint registration 

### ISSUE THREAD

**Issue by mrsaicharan1** [singingwolfboy/flask-dance#224]
@singingwolfboy I'm trying to implement Twitter authentication and flask_dance throws out an error saying that
`AssertionError: A name collision occurred between blueprints <flask_dance.consumer.oauth1.OAuth1ConsumerBlueprint object at 0x7f29b2ab1860> and <flask_dance.consumer.oauth1.OAuth1ConsumerBlueprint object at 0x7f29b3418198>. Both share the same name "twitter". Blueprints that are created on the fly need unique names. ` . Can't seem to find out where I'm registering the blueprint twice. For further reference , here's the link to my PR to the repo. [fossasia/open-event-server#5600](https://github.com/fossasia/open-event-server/pull/5600). Would be great if you could help me out here :)

**Comment by singingwolfboy** [comment]
I skimmed your pull request, and I don't see the problem. This is also not the place for requests like this. GitHub issues are for filing issues/bugs with the Flask-Dance project itself, not to ask for help with your implementation. As a result, I'm closing this pull request.

**Comment by daenney** [comment]
You're calling `make_twitter_blueprint` twice, once in `__init__.py` and once in `auth.py`.

**Comment by mrsaicharan1** [comment]
@daenney I'm able to see only one `make_twitter_blueprint`. How exactly am I calling it two times?
