### ISSUE TITLE
Flask-Dance 2.0

### ISSUE THREAD

**Issue by singingwolfboy** [singingwolfboy/flask-dance#231]
We're approaching the 2.0 release for Flask-Dance. Incrementing the major version is an opportunity to make backwards-incompatible changes. Here are some proposed changes we could make:

* drop `next` redirect (PR #230)
* consistent config names for pre-set configurations (PR #229)
* multithreading support? (issue #205)
* auto-refreshing tokens? (issue #143)
* remove special treatment of `expires_at` parameter? (https://github.com/oauthlib/oauthlib/issues/568)

We certainly don't have to make _all_ of these changes in version 2.0. In particular, while I would _love_ to get multithreading working, I don't even know how to properly test the code to verify it.

If anyone else has ideas of what to include for version 2.0, please add a comment to this issue.

**Comment by daenney** [comment]
I think #205 will risk delaying 2.0 a lot. It seems to require changes in the supporting libraries we use, like lazy. We'd need to vet any other supporting library too to ensure it's thread-safe and do a lot of testing on our side to reveal any potential threading bugs. People generally don't think about thread safety when writing Python so this might prove to be a pretty big task requiring many changes in both our code and our dependencies.

There's all kinds of nastiness to keep in mind too, for example `counter = 1` is thread safe, but `counter = counter + 1` is not. CPython guarantees a lot of actions on built-in types and single operations to be thread safe, but that is an implementation detail of CPython and not necessarily true for PyPy etc.

Given how bad it could be if we were to leak things like tokens across threads we should be really careful about doing this.

**Comment by singingwolfboy** [comment]
> I would much prefer not supporting this and recommending people run this in a multiprocess/prefork mode instead, which is what normally happens when you run with mod_wsgi or uwsgi.

Totally fair. Any chance I could ask you to put this recommendation into our docs? 😄

**Comment by daenney** [comment]
Sure, will do!

**Comment by daenney** [comment]
I just realised something... Flask itself remains thread safe due to its use of context locals and the app and request contexts. So in theory, we should be too as long as nothing is done outside of a context (aside from loading settings). I'm just not sure how this interacts with the import machinery and any supporting library but as long as we create the Oauth client within at least the app context we shouldn't risk leaking anything across threads.

**Comment by singingwolfboy** [comment]
Discussion about how to fix multi-threading probably belongs in #205, not here 😄

**Comment by daenney** [comment]
Good point :laughing:. I've replied there. Lets see what happens.
