### ISSUE TITLE
Azure provider and auto_refresh_url

### ISSUE THREAD

**Issue by mrsixw** [singingwolfboy/flask-dance#232]
Just wondering if there was a reason why the azure provider doesn't seem to have auto_refresh_url configured?

**Comment by singingwolfboy** [comment]
@steven-martins, you're the maintainer for the Azure provider. Is there a reason?

I don't know anything about Azure, but my guess is that we just missed it. Would you like to send a pull request to add it?

**Comment by mrsixw** [comment]
Thanks for the quick response! 

I guess that was really my question - is there a reason why it would be anymore complex than just adding in `auto_refresh_url` (possibly some `auto_refresh_kwargs`) to the call to `OAuth2ConsumerBlueprint()`? 

I'll admit I I'm yet to try this - but I am at the stage where my app need to either have this added to flask-dance or I need to handle `TokenExpiredError` in the app, so I thought I would start the dialog.

**Comment by singingwolfboy** [comment]
I don't _think_ it would be any more complex than that. Let's put it this way -- if you discover that it's not that simple, or that the `auto_refresh_url` parameter doesn't work as well as it should, that might be a bug in Flask-Dance, and you should report it so we can try to fix it. 😄

**Comment by mrsixw** [comment]
I'll give it a go 👍

**Comment by singingwolfboy** [comment]
@mrsixw any progress on this?

**Comment by mrsixw** [comment]
No, I've not had time to take a proper look yet.

**Comment by singingwolfboy** [comment]
I'm closing this issue due to a lack of updates.
