### ISSUE TITLE
Bump OAuthLib requirement to 3.0.1

### ISSUE THREAD

**Issue by JellyWX** [singingwolfboy/flask-dance#236]
Potentially this is an issue with pip or apt rather than flask-dance but I'm posting here just in case.

Fought with this for 5 hours yesterday having `InvalidClientError (invalid_client)` when moving from one prod server to another. Eventually ruled out all issues relating to config and code, so checked all my pip installs and found the difference was in the version of oauthlib.

On oauthlib 2.1.0, the discord blueprint fails with `invalid_client` every time even with a correct client ID and secret.

Again, I've installed flask dance many many times and never had this issue, so maybe this is an issue with pip or apt conflicting versions

**Comment by JellyWX** [comment]
title should state this is regarding the Discord blueprint, can't seem to fix this from mobile. This issue may be present on other blueprints also but I didn't check

**Comment by daenney** [comment]
The versions aren't pinned: https://github.com/singingwolfboy/flask-dance/blob/master/requirements.txt so when you `pip install` Flask-Dance it'll install the newest version, if no other version is already installed that satisfies the dependency. This can happen if you OS happens to provide it, which Debian/Ubuntu do: https://packages.debian.org/stretch/python-oauthlib.

You shouldn't be mix-matching Python packages between those provided by the OS and Flask-Dance, which isn't packaged. You can use a virtualenv, a Docker container or a debhelper like dh-virtualenv to properly package this up.

**Comment by JellyWX** [comment]
Ah, that explains it. I almost always use venv but this time didn't. Highest version in apt was installed which is 2.6. Thanks for clarification
