### ISSUE TITLE
Flask Dance and url_for on Heroku

### ISSUE THREAD

**Issue by joshua-s** [singingwolfboy/flask-dance#248]
I am using your lovely library Flask Dance in an app on Heroku, but receiving an issue: generated redirect URLs use http instead of https. The odd thing is that any usage of `url_for` with `_external=True` outside of Flask Dance generates an https URL. And, according to the logs, the correct `X-Forwarded-Proto` is being sent.

I have read your article on proxies and set `PREFERRED_URL_SCHEME`: https://flask-dance.readthedocs.io/en/latest/proxies.html

Please let me know what information you would need to debug this.

**Comment by singingwolfboy** [comment]
Are you able to share your code? That would be ideal for helping to diagnose this issue.

If not, can you answer a few questions:

* Are you using one of the pre-set configurations, or are you creating your own blueprint with a different OAuth provider? Which provider are you using?
* If you deploy one of the quickstart projects on Heroku, are you able to reproduce the problem? If so, how?
* Can you try making a minimal test-case that reproduces your problem, and post that publicly somewhere?

**Comment by joshua-s** [comment]
@singingwolfboy thanks for the swift response.

1. I am using the Google and Facebook presets
2. I tried the Google Quickstart and the Facebook + SQLAlchemy Quickstart--both worked.
3. I chopped my codebase down to just the stuff surrounding Flask-Dance:
  - https://github.com/joshua-s/flask-dance-error
  - https://safe-castle-39157.herokuapp.com

One other thing that I did not mention before, but could have an impact: I am using docker.

**Comment by joshua-s** [comment]
@singingwolfboy did you get a chance to check these out?

**Comment by stroebs** [comment]
I'm getting this issue as well now...
Minimal configuration and yet Flask-Dance still generates a http URL and causes an OAuth error. It was working absolutely fine back in March but now no longer.

**Comment by stroebs** [comment]
@singingwolfboy @joshua-s 
My previous comment "It was working absolutely fine back in March" made me think about package versions. I downgraded `werkzeug` to `0.14.1`, before they released massive changes in their `0.15.0` release. URLs are now working fine again.
My `requirements.txt`:
`Flask==1.0.2
six
Flask-Dance==1.4.0
werkzeug==0.14.1`

**Comment by singingwolfboy** [comment]
That's interesting! I know that `werkzeug` changed the [`ProxyFix`](https://werkzeug.palletsprojects.com/en/0.15.x/middleware/proxy_fix/#module-werkzeug.middleware.proxy_fix) middleware with the 0.15 release, and that could be the reason why Flask-Dance doesn't know that it's running on HTTPS.

Previously, you had to use `ProxyFix(num_proxies=1)`. Now, you need to use `ProxyFix(x_for=1, x_proto=1)`. You should also update your imports to `werkzeug.middleware.proxy_fix.ProxyFix`.

Does that fix the problem on `werkzeug` 0.15?

**Comment by stroebs** [comment]
@singingwolfboy That actually works well.

Changes I made:
1) Change import to: `from werkzeug.middleware.proxy_fix import ProxyFix`
2) Change ProxyFix config call to `app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1)`

App working fine now, reverted all my attempted fixes.

**Comment by singingwolfboy** [comment]
Great! @joshua-s, does this solve your problem, as well?

**Comment by joshua-s** [comment]
@singingwolfboy apologies for the delay: somehow, I missed this. Those changes do indeed solve the issue for me!

Closing because this was not a flask dance issue.
