### ISSUE TITLE
Okta provider not working

### ISSUE THREAD

**Issue by RichardCullen** [singingwolfboy/flask-dance#263]
Trying to use the Okta provider (which doesn't have an example to follow) 

```
import os
from flask import Flask, redirect, url_for
from flask_dance.contrib.okta import make_okta_blueprint, okta
from flask_dotenv import DotEnv

app = Flask(__name__)
env = DotEnv(app)

app.secret_key = os.environ.get("FLASK_SECRET_KEY", "supersekrit")
okta_bp = make_okta_blueprint(
    client_id=app.config["OKTA_OAUTH_CLIENT_ID"],
    client_secret=app.config["OKTA_OAUTH_CLIENT_SECRET"],)
app.register_blueprint(okta_bp, url_prefix="/login")


@app.route("/")
def index():
    if not okta.authorized:
        return redirect(url_for("okta.login"))
    resp = okta.get("/user")
    assert resp.ok
    return "You are @{login} on Okta".format(login=resp.json()["login"])


if __name__ == "__main__":
    app.run(debug=True, use_reloader=True)
```

Gives me the following error:
```
builtins.AttributeError
AttributeError: 'NoneType' object has no attribute 'lower'

Traceback (most recent call last)
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\app.py", line 2328, in __call__
return self.wsgi_app(environ, start_response)
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\app.py", line 2314, in wsgi_app
response = self.handle_exception(e)
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\app.py", line 1760, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\_compat.py", line 36, in reraise
raise value
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\app.py", line 2311, in wsgi_app
response = self.full_dispatch_request()
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\_compat.py", line 36, in reraise
raise value
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
rv = self.dispatch_request()
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask\app.py", line 1818, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\work\python\okta-flask-example\env\lib\site-packages\flask_dance\consumer\oauth2.py", line 201, in login
self.authorization_url, state=self.state, **self.authorization_url_params
File "C:\work\python\okta-flask-example\env\lib\site-packages\requests_oauthlib\oauth2_session.py", line 158, in authorization_url
**kwargs), state
File "C:\work\python\okta-flask-example\env\lib\site-packages\oauthlib\oauth2\rfc6749\clients\web_application.py", line 90, in prepare_request_uri
redirect_uri=redirect_uri, scope=scope, state=state, **kwargs)
File "C:\work\python\okta-flask-example\env\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 70, in prepare_grant_uri
if not is_secure_transport(uri):
File "C:\work\python\okta-flask-example\env\lib\site-packages\oauthlib\oauth2\rfc6749\utils.py", line 94, in is_secure_transport
return uri.lower().startswith('https://')
AttributeError: 'NoneType' object has no attribute 'lower'
```
because `self.authorization_url` is empty.

Any ideas?

**Comment by daenney** [comment]
Looks like we have a bug: https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/contrib/okta.py.

`authorization_url` is defined as optional with a default in the docs but the code doesn't actually apply the default.

We need a `authorization_url = authorization_url or "/okta/authorized"`. Additionally the docs have it defined as `authorized_url` whereas the code wants `authorizaiton_url`.

You can get your own code to work by explicitly passing in an `authorization_url` to `make_okta_blueprint` for now.

**Comment by daenney** [comment]
Mmm, although, that should happen by default if you don't define it. That's curious.

**Comment by daenney** [comment]
@RichardCullen What versions of Flask, Flask-Dance and oauthlib are you using? The output of `pip freeze` for example would be helpful.

**Comment by RichardCullen** [comment]
```
Flask==1.0.3
Flask-Dance==2.1.0
oauthlib==3.0.1
```

**Comment by daenney** [comment]
@singingwolfboy I'm puzzled by this one.

```python
def make_okta_blueprint(
...
    authorization_url=None,
):
    """
        authorized_url (str, optional): the URL path for the ``authorized`` view.
            Defaults to ``/okta/authorized``.
    """
    okta_bp = OAuth2ConsumerBlueprint(
...
        authorization_url=authorization_url,
```

I believe the arg should be `authorized_url`, so people can define their local view and override the default that `OAuth2ConsumerBlueprint` will give, but `authorization_url` should definitely not be `None`, it should be pointing to something like `https://{yourOktaDomain}/oauth2/v1/authorize` where `base_url` should probably be set to `https://{yourOktaDomain}/` or something along those lines.

I can't see the Okta blueprint working in its current state.

**Comment by daenney** [comment]
@RichardCullen If you pass in `base_url`, `authorization_url` and `token_url` as shown in the comment above you should be able to get past the issue. But we definitely need to take a closer look at the Okta blueprint.

**Comment by RichardCullen** [comment]
Setting `base_url`, `authorization_url` and `token_url` progress things, but now I'm getting:
```
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) The grant was issued for another authorization server.
```

**Comment by daenney** [comment]
@RichardCullen: https://devforum.okta.com/t/the-grant-was-issued-for-another-authorization-server-how-long-do-refresh-tokens-last/4736

**Comment by RichardCullen** [comment]
OK, making progress...!
Now we are progressing, but it appears that `resp = okta.get("/user")` is returning empty

**Comment by daenney** [comment]
I'm afraid we can't do much about that. You'll need to refer to the Okta documentation and make sure you're querying the right endpoints: https://developer.okta.com/docs/api/resources/oidc/#userinfo

It looks like what you need is `/userinfo`.

**Comment by RichardCullen** [comment]
That's it! Thank you!
`resp = okta.get(app.config["OKTA_ORG_URL"]+"/oauth2/v1/userinfo")`

**Comment by singingwolfboy** [comment]
@tnolan8: you're the maintainer for the Okta configuration. Can you take a look at this issue, and see what the problem is?

**Comment by tnolan8** [comment]
@RichardCullen,@singingwolfboy - Currently at work but I'll try make some time over the next night/two to see if I can see what's going on!

**Comment by daenney** [comment]
If `OKTA_ORG_URL` is how it's meant to be configured the blueprint should load that into `base_url`. Because you should be able to do `okta.get("/userinfo")` and have it construct the right URL, not have to interpolate `OKTA_ORG_URL` yourself.

**Comment by tnolan8** [comment]
If that's the case (I can't remember off the top of my head but I'll look into it) then agreed, if so I'll create a PR to fix it + put up and example!

**Comment by tnolan8** [comment]
Just a quick note, I was able to get this to a point last night where it looked like it was auth'ing fine but when I was trying to make requests post authenticating they kept 401'ing, just need to figure out why that is. Unfortunately somethings come up however and I have to fly out of the country for the weekend so I'm not going to get around to it this weekend, apologies. I will get this fixed next week though!

**Comment by singingwolfboy** [comment]
Looks like Okta is a tricky provider to support, since they are _so_ flexible that it's hard to write a pre-set configuration! We decided in #267 that the best way to support Okta is to actually _remove_ the pre-set configuration, and provide better documentation for how to use the `OAuth2ConsumerBlueprint` class directly.

If anyone has any thoughts on how best to write that documentation, I suggest reaching out to @tnolan8 -- I've agreed to help with writing it as well, but I've never used Okta before, so I'm not the best person to talk to. 😄

@RichardCullen: Sounds like you got Flask-Dance and Okta to work together, which is great! I suggest that you talk to @tnolan8 and follow this issue, since it appears that you might need to modify your code in the future, once the Okta pre-set configuration is removed. I suspect that the changes you need to make will actually be pretty small, since that configuration doesn't actually _do_ very much.

**Comment by singingwolfboy** [comment]
@tnolan8 any progress on making a pull request to remove the Okta provider and add documentation to support them, instead?

**Comment by tnolan8** [comment]
@singingwolfboy Sorry, been really busy wrapping up with a thesis and what not at the moment, I'll get around to removing the Okta configuration tonight but the documentation and what not might have to wait a little while!
