### ISSUE TITLE
Does Flask-Dance support the Oauth2 "Authorization Code Grant" flow?

### ISSUE THREAD

**Issue by adrianocr** [singingwolfboy/flask-dance#265]
The flow is listed here: https://tools.ietf.org/html/rfc6749#section-4.1
Specifically I ask because that's how Shopify does oauth: https://help.shopify.com/en/api/getting-started/authentication/oauth#the-oauth-flow

I'm having a hard time seeing how to use Flask-Dance to go through that flow.

**Comment by daenney** [comment]
This is exactly what Flask-Dance does, it's pretty much its only job :smile:.

The problem you'll run into right now is that we don't support Shopify out of the box yet. But take a look at the GitHub one for example: https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/contrib/github.py and you can create a new one for Shopify based on that.

The GitHub quickstart code: https://github.com/singingwolfboy/flask-dance-github will probably also be helpful to take a look at.

I'm happy to try and help you with more specific question, but on the topic of "does Flask-Dance support OAuth authorization code grant" the answer is simply "yes".
