### ISSUE TITLE
Google Oauth Erroring Out After Warning

### ISSUE THREAD

**Issue by manasgaur1** [singingwolfboy/flask-dance#276]
Hey... Need your help.

My Google Authentication was working fine last week but has started erroring today. The library gives the following Warning

> Warning: Scope has changed from "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile" to "openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

Then it errors out at:
> validate_token_parameters(params)

Here is my blueprint code:
`google_bp = make_google_blueprint(
        client_id=flask_app.config['GOOGLE_CLIENT_ID'],
        client_secret=flask_app.config['GOOGLE_CLIENT_SECRET'],
        redirect_url='/authorized',
        scope=["https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/userinfo.profile"]
    )`

I feel this might be related to Google deprecating the GooglePlus API. The strange point is that this is working with just userinfo.profile, but I need the email also.

I am using Flask-Dance==1.3.0 with python 2.7.10

**Comment by daenney** [comment]
> scope, which in a basic request should be openid email. (Read more at scope.) 
https://developers.google.com/identity/protocols/OpenIDConnect#sendauthrequest

Looks like all you'd need to do is add 'openid', to the scopes you're requesting and then the validation should pass.

@singingwolfboy Looking at the Google docs we should update the default scopes for the Google blueprint now.

**Comment by manasgaur1** [comment]
@daenney Thanks for your advice. It seems to be working now. I will complete a few checks though.

**Comment by manasgaur1** [comment]
Closing the issue. Thank you @daenney for your recommendation.
