### ISSUE TITLE
connect_via with flask_dance

### ISSUE THREAD

**Issue by MUGABA** [singingwolfboy/flask-dance#278]
@cust_bp.route('/api/v1/customers/facebook', methods = ['POST'])
def facebook_login():
    if not facebook.authorized:
        return redirect(url_for('facebook.login'))

    account_info = facebook.get('account/settings.json')
    account_info_json = account_info.json()

    return '<h1>Your facebook name is @{}'.format(account_info_json['screen_name'])

@oauth_authorized.connect_via(facebook_blueprint)
def facebook_logged_in(blueprint, token):

    account_info = blueprint.session.get('account/settings.json')

    if account_info.ok:
        account_info_json = account_info.json()
        username = account_info_json['screen_name']

        query = Customers.query.filter_by(username=name)

        try:
            user = query.one()
        except NoResultFound:
            user = User(username=username)
            db.session.add(user)
            db.session.commit()

        login_user(user)

**Comment by daenney** [comment]
This is a, badly formatted, code dump. I'm not sure what kind of help you're trying to get here but without any context as to what you're trying to do and what isn't going your way we're not going to be able to help you.

**Comment by MUGABA** [comment]
Thanks for that your concerned but i was missing Blinker in my variables i
fixed it latter
Thanks Mugaba
