### ISSUE TITLE
Flask-Dance abandoned 

### ISSUE THREAD

**Issue by ElPapi42** [singingwolfboy/flask-dance#291]
is this project abandoned ?

**Comment by wgwz** [comment]
I don't think that's the case at all. The last release was on 10/21/2019 and v3.0.0. And as major release and a project I've been following for a few years, I think the library is just fairly stable for what it provides at this point.

And taking a look back at the changelog, it's pretty clear there's been consistent work in 2019.

**Comment by singingwolfboy** [comment]
@wgwz is correct. This project is actively maintained, and not abandoned.
