### ISSUE TITLE
Is there any way we can integrate flask-dance with Flask-Security?

### ISSUE THREAD

**Issue by JagdishKolhe** [singingwolfboy/flask-dance#298]
Is there any way we can integrate flask-dance with Flask-Security

**Comment by singingwolfboy** [comment]
Flask-Security uses Flask-Login, and Flask-Dance already works quite nicely with Flask-Login (as shown in multiple quickstart examples). Nonetheless, I just created [a new quickstart that uses Flask-Security](https://github.com/singingwolfboy/flask-dance-google-security-sqla), so you can see how to make it work. You'll notice that it's almost identical to the existing quickstart that uses Flask-Login.
