### ISSUE TITLE
Heroku oauth issue

### ISSUE THREAD

**Issue by naoned44** [singingwolfboy/flask-dance#299]
Hi,

when trying to signin with heroku, the heroku.authorized flag stay to false.
If I check session data, the property heroku_oauth_state is added after loging but no further calls to heroku api can be done: the authentication token is not set in header 

I reproduce this issue with the singingwolfboy/flask-dance-heroku project.

Best regards

**Comment by Bruno-Ladure** [comment]
Seems the issue due to an HTTP redirect even if OAUTHLIB_INSECURE_TRANSPORT is set to True.
With HTTPS it's working. The issue can be close
