### ISSUE TITLE
Example using a YT API after Google auth

### ISSUE THREAD

**Issue by leto** [singingwolfboy/flask-dance#3]
I have been using flask-dance and it is pretty awesome! I am using it to connect to Google with various YouTube scopes and the oauth tokens get stored in my database with the proper foreign keys to my user table.

Currently I am trying to tie together flask-dance with one of these examples:

https://github.com/youtube/api-samples/tree/master/python

Would you mind giving some advice on using my Flask-Dance google blueprint to accomplish one of those examples? I can prepare it as a Pull Request for the docs, if you would like.

**Comment by leto** [comment]
Turns out I've answered my question. It was much simpler than I thought!

**Comment by singingwolfboy** [comment]
Can you post the answer somewhere and link to it from this issue, so that other people in the future will be able to see what you did?

**Comment by leto** [comment]
For example, from the Flask-Dance manual, it was not clear *what* to do with the ```google``` object, until I learned that I could simple call ```.get()``` with an API URL. For instance, the line below grabs all the interesting stats about a YouTube channel, including views/subscribers/videos uploaded/etc.

```
channels = google.get('https://www.googleapis.com/youtube/v3/channels?part=statistics,id,snippet,contentOwnerDetails,status&mine=true').json()
```
