### ISSUE TITLE
google.post to gmail api not properly executing

### ISSUE THREAD

**Issue by Symply13** [singingwolfboy/flask-dance#301]
Hey! I have been banging my head against the desk for hours trying to figure this out...  

code: 
```python
message = MIMEText(msgbody,'html')
message['to'] = recipient
message['from'] = sender
message['subject'] = subject
gmailbytes = base64.urlsafe_b64encode(message.as_bytes())
gmailstring = gmailbytes.decode()
gmailready = json.dumps({'raw':gmailstring}) 
print(gmailready)
headers = {'Content-Type': 'message/rfc822'}
resp = google.post(url='https://www.googleapis.com/upload/gmail/v1/users/me/messages/send', headers=headers, data=gmailready)
```

While using Google's API explorer, if I copy and paste the output of gmailready directly into the API explorer, the messages sends as expected... but when executing from google.post() command, it gives me the error: 

```json
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalidArgument",
    "message": "Recipient address required"
   }
  ],
  "code": 400,
  "message": "Recipient address required"
  }
 }
```

if I don't add the headers to the post call, and execute:
`resp = google.post(url='https://www.googleapis.com/upload/gmail/v1/users/me/messages/send', data=gmailready)`

it gives the error: 

```json
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badContent",
    "message": "Media type 'application/octet-stream' is not supported. Valid media types: [message/rfc822]"
   }
  ],
  "code": 400,
  "message": "Media type 'application/octet-stream' is not supported. Valid media types: [message/rfc822]"
 }
}
```

I've tried changing headers to `application/json` (per the google api documentation) and it still complains it wants the `message/rfc882` Where am I going wrong at?

Thank you in advance!

**Comment by daenney** [comment]
Have you tried passing in a headers direct in your `post` call, `google.post(... {'Content-Type': 'message/rfc822'} ...)`?

**Comment by daenney** [comment]
> While using Google's API explorer, if I copy and paste the output of gmailready directly into the API explorer, the messages sends as expected... but when executing from google.post() command, it gives me the error:

I don't know why that is. But in order to find out, it's probably the quickest to use your browsers Dev Tools, reload the API explorer page, do the request and see what gets sent. It might be that the API explorer injected a value somewhere for you, which you'd now be able to see, and it would also tell you which headers it ends up sending.

**Comment by Symply13** [comment]
Thank you for the response!  I tried what you recommended and messed around with the headers for a few hours, and using standard request library which kept resulting in an auth error: 
> {
>  "error": {
>   "errors": [
>    {
>     "domain": "global",
>     "reason": "authError",
>     "message": "Invalid Credentials",
>     "locationType": "header",
>     "location": "Authorization"
>    }
>   ],
>   "code": 401,
>   "message": "Invalid Credentials"
>  }
> }

I kept searching the interwebs and came across a stackoverflow post that did the trick!
https://stackoverflow.com/questions/49290399/400-error-recipient-address-required-curl

interestingly enough, googleapi docs say you have to use base64.urlsafe_b64encode(message.as_string()) to encode the ENTIRE message before sending which is incorrect.  

Apparently you only need to base64 encode the subject and message of the email for the gmail api to read the recipient info and set the headers content type to message/rfc822.  Final code to make it work: 

> def encode(v):
>         byte_msg = v.encode(encoding="UTF-8")
>         byte_msg_b64encoded = base64.b64encode(byte_msg)
>         return byte_msg_b64encoded.decode(encoding="UTF-8")
>     message = "To: " + recipient + "\n"
>     message += "From: " + sender + "\n"
>     message += "Subject: =?utf-8?B?" + encode(subject) + "?=\n"
>     message += "Date: " + formatdate(localtime=True) + "\n"
>     message += "Content-Type: multipart/alternative; boundary=boundaryboundary\n\n"
>     message += "--boundaryboundary\n"
>     message += "Content-Type: text/plain; charset=UTF-8\n"
>     message += "Content-Transfer-Encoding: base64\n\n"
>     message += encode(msgbody) + "\n\n"
>     message += "--boundaryboundary"
>     headers = {"Content-Type": "message/rfc822"}
>     resp = google.post(url='https://www.googleapis.com/upload/gmail/v1/users/me/messages/send', headers=headers, data=message)
   
Works great now.  Thanks for making flask-dance!!!! :-)

**Comment by daenney** [comment]
Glad you managed to figure it out!
