### ISSUE TITLE
OAuth2ConsumerBlueprint & redirect_uri

### ISSUE THREAD

**Issue by macmule** [singingwolfboy/flask-dance#312]
Does OAuth2ConsumerBlueprint support redirect_uri's?

Cannot see redirect_uri in the class: https://github.com/singingwolfboy/flask-dance/blob/main/flask_dance/consumer/oauth2.py#L23

Was looking to use flask-dance with okta & need a redirect_uri

**Comment by singingwolfboy** [comment]
The `redirect_uri` is the URL where your Flask app will be running. Specifically, it should point to the `authorized` view in the `OAuth2ConsumerBlueprint` blueprint. It's not defined in the blueprint, because it's not managed by the blueprint.

For example, if you have your Flask app running at `https://example.com`, and you name your blueprint `okta` and mount it  using `url_prefix="/login`, then the `redirect_uri` should be `https://example.com/login/okta/authorized`.

Does that make sense?

**Comment by macmule** [comment]
@singingwolfboy thanks, so Okta complains with:

`The 'redirect_uri' parameter must be an absolute URI that is whitelisted in the client app settings.`

And in the settings in Okta the 'redirect_uri' defaults to: http://127.0.0.1:5000/oidc/callback (as an example).

And I've just realised I'm conflating OAuth & OIDC, so will create an OAuth app in Okta for this.

**Comment by macmule** [comment]
@singingwolfboy, thank you.. actually an OpenID connect app worked.. just needed to make sure that the request_uri was built as per what you said.

Now to see about putting this infront of flask-admin!

**Comment by macmule** [comment]
Sorry, to reopen this.

But if the app is running locally as http://0.0.0.0:5000.. yet we're using k8s & directing via a public DNS entry.. how do we override the URL where your Flask app will be running?

**Comment by macmule** [comment]
> The `redirect_uri` is the URL where your Flask app will be running. Specifically, it should point to the `authorized` view in the `OAuth2ConsumerBlueprint` blueprint. It's not defined in the blueprint, because it's not managed by the blueprint.
> 
> For example, if you have your Flask app running at `https://example.com`, and you name your blueprint `okta` and mount it using `url_prefix="/login"`, then the `redirect_uri` should be `https://example.com/login/okta/authorized`.
> 
> Does that make sense?

Is there a way to override the URL which flask-dance see’s the app as running at?

So the app is running on 0.0.0.0, but you pass a FQDN (for example)

**Comment by singingwolfboy** [comment]
Does this help? https://flask-dance.readthedocs.io/en/latest/proxies.html

**Comment by macmule** [comment]
@singingwolfboy maybe, I’m using gunicorn & are receiving the needed headers etc.

Redirect routes are working as expected, my thoughts were that the `redirect_uri` is was being built with the details that the flask app is running under vs how it’s being accessed.

Is there anyway to get the `redirect_uri` printed out? It’s more than possible that I’m hitting something else.

**Comment by macmule** [comment]
oh & locally on kubernetes this works too.. so the issue does seem to be when ingress etc is involved.

**Comment by macmule** [comment]
@singingwolfboy thanks again.. & for this project :)

So.. the issue was  that as we are SSL offloading i needed to specify http:// in the request_uri as well as "OAUTHLIB_INSECURE_TRANSPORT".
