### ISSUE TITLE
Surfacing assignment errors

### ISSUE THREAD

**Issue by macmule** [singingwolfboy/flask-dance#313]
Hi folks,

How do you go about surfacing assignment errors from .authorized?

`OAuth 2 authorization error: access_denied description: User is not assigned to the client application. uri: None`

I'm testing & seeing the above (correctly), & would like to present that error in a page.

**Comment by daenney** [comment]
I think you're looking for https://flask-dance.readthedocs.io/en/latest/signals.html#flask_dance.consumer.oauth_error

**Comment by daenney** [comment]
You can also do something like

```python
from oauthlib.oauth2.rfc6749.errors import xxxx

ui = Blueprint('ui', __name__, url_prefix='/')

@ui.errorhandler(xxx)
def yyyy(_):
```

**Comment by macmule** [comment]
Thanks @awiddersheim
