### ISSUE TITLE
Custom provider: get path not using base_url for keycloak setup

### ISSUE THREAD

**Issue by JackDra** [singingwolfboy/flask-dance#325]
I am working on getting flask-dance to work with keycloak as a "custom" authenticator.

I have set up an `OAuth2ConsumerBlueprint` with the required args with everything working fine. 
But when I perform a `session.get` request to the authenticator, I have to pass the path relative to `http://localhost/`, instead of the `base_url` path: `http://localhost/auth/realms/test_realm/`. 
I.e. I need to pass in 
`.session.get("/auth/realms/{MY_REALM}/protocol/openid-connect/userinfo")`
instead of
`.session.get("/protocol/openid-connect/userinfo")`

It could possibly be due to the fact that I hacked OAuth to skip the https check just for dev testing:
https://github.com/oauthlib/oauthlib/blob/d54965b86ce4ede956db70baff0b3d5e9182a007/oauthlib/oauth2/rfc6749/utils.py#L79-L83
I replaced `https` with `http`

FYI, If anyone is interested (and it hasn't been done yet), I can look into contributing keycloak as a provider if I can get this working... The current code is (replace your_... with your keycloak configuration):

```
KEYCLOAK_ADDRESS = "http://localhost/auth/realms/your_realm/"
KEYCLOAK_TOKEN_PATH = KEYCLOAK_ADDRESS + 'protocol/openid-connect/token'
KEYCLOAK_AUTH_URL = KEYCLOAK_ADDRESS + 'protocol/openid-connect/auth'


keycloak = OAuth2ConsumerBlueprint(
    "keycloak", __name__,
    client_id="your_keycloak_client_id",
    client_secret='your_secret_key',
    base_url=KEYCLOAK_ADDRESS,
    token_url=KEYCLOAK_TOKEN_PATH,
    authorization_url=KEYCLOAK_AUTH_URL,
    redirect_url='/flask_backend/login'
)
app.register_blueprint(keycloak, url_prefix="/flask_backend/login")

@app.route("/flask_backend/login")
def index():
    if not keycloak.session.authorized:
        return redirect(url_for("keycloak.login"))
    resp = keycloak.session.get(
        "/auth/realms/test_realm/protocol/openid-connect/userinfo")
    assert resp.ok
    return "You are @{login} on KeyCloak".format(login=resp.json()["preferred_username"])
```

When setting up your client on keycloak, make sure to setup your clients access type to Confidential, then in the credentials tab, you will find your `secret` key which you will use for `your_secret_key`

**Comment by daenney** [comment]
The `request` method uses `base_url.relative()` when construction a URL. base_url itself is an instance of URLObject: https://urlobject.readthedocs.io/en/latest/quickstart.html

When you pass in a relative URL starting with a `/` it discards the existing path of the URLObject. If you want the URL you're passing into `session.get()` to be constructed as relative to the host+path of `base_url`, you need to omit the leading slash.

What you want is `.session.get("protocol/openid-connect/userinfo")`

**Comment by JackDra** [comment]
> I think what you want is .session.get("protocol/openid-connect/userinfo").

DOH' ..... that makes sense.... thanks!
