### ISSUE TITLE
Allow a way to include client_id while fetching token

### ISSUE THREAD

**Issue by abrahamfrancis** [singingwolfboy/flask-dance#329]
I was trying to use this with Basecamp api. And when the OAuth2ConsumerBlueprint tries to fetch the token, I get the following error:
```
oauthlib.oauth2.rfc6749.errors.CustomOAuth2Error: (Missing client_id query parameter.)
```
I found a fix. You can add a `include_client_id=True` parameter in the call to fetch token [here](https://github.com/singingwolfboy/flask-dance/blob/d88ac942366679ecdf65e7b654cf3dbea794992a/flask_dance/consumer/oauth2.py#L256).

Is there a better way to fix this issue?

**Comment by singingwolfboy** [comment]
You can set that in the `token_url_params`, [like we do with the LinkedIn configuration](https://github.com/singingwolfboy/flask-dance/blob/465879af05f2b6dab333c1fcd45a780524151c92/flask_dance/contrib/linkedin.py#L66). Would you like to send a pull request to add Basecamp as a pre-set configuration?

**Comment by abrahamfrancis** [comment]
Thanks! That worked.
I'm sorry. I am not as familiar with this.
