### ISSUE TITLE
ImportError on sqla.py

### ISSUE THREAD

**Issue by ananthb** [singingwolfboy/flask-dance#33]
When I try to use the OAuthConsumerMixin to save my OAuth credentials to my database, I'm getting an import error from the sqla.py file in the flask_dance.consumer.backend module. The specific error I'm getting is 'ImportError: No module named sqlalchemy_utils'. Do I need to install another package or is this a type in the code?

**Comment by singingwolfboy** [comment]
[`sqlalchemy_utils`](https://sqlalchemy-utils.readthedocs.org/en/latest/) is a dependency of the SQLAlchemy backend. Note that the installation instructions state that if you want to use the SQLAlchemy backend, you should install the package with `pip install flask-dance[sqla]` -- the dependencies are noted [in the `setup.py` file](https://github.com/singingwolfboy/flask-dance/blob/master/setup.py#L62).
