### ISSUE TITLE
How to confirm unauthorized state after logging out when testing?

### ISSUE THREAD

**Issue by HelloRusk** [singingwolfboy/flask-dance#337]
Hi. 

I read [the document about testing](https://flask-dance.readthedocs.io/en/latest/testing.html) and successfully wrote the mock test.
However I still can't figure out how to check you are logged out after GET `/login`. My code is like below...

```python
def test_logout(monkeypatch):
    storage = MemoryStorage({"access_token": "fake-token"})
    monkeypatch.setattr(spotify_bp, "storage", storage)

    with app.test_client() as client:
        res = client.get("/logout", base_url="https://example.com")

    assert res.status_code == 302
    assert res.headers["Location"] == "https://example.com/" # redirect to top page

    # how to assert I am logged out now ....??
```

**Comment by daenney** [comment]
Your logout action needs to clear the token, usually something like `del blueprint.token` and a `session.clear()`. There's some documentation on logging out here: https://flask-dance.readthedocs.io/en/latest/logout.html

If you want to test whether you're logged out or not, you can check what `blueprint.authorized` now returns. It should be `False`.

**Comment by HelloRusk** [comment]
Thanks!
