### ISSUE TITLE
Discord oauth2 not working properly

### ISSUE THREAD

**Issue by MakufonSkifto** [singingwolfboy/flask-dance#341]
When I try to login into my website, it logs in. But when I click an another link that needs my discord login, I need to login again for some reason and its just an infinite loop. How can I fix this?

**Comment by singingwolfboy** [comment]
Sounds like the OAuth information is not being saved, or is not correctly associated with the user. What token storage are you using? Have you compared your code to some of the same quickstarts, such as https://github.com/singingwolfboy/flask-dance-google-sqla ?

**Comment by MakufonSkifto** [comment]
we are using flask session for storage

**Comment by singingwolfboy** [comment]
@michaeldel, you're the maintainer for the Discord provider. Do you have any idea what's going on here?

**Comment by MakufonSkifto** [comment]
@singingwolfboy We fixed the issue by using Flask-SqlAlchemy but there is still an another problem. Flask-Dance doesn't add more than 1 entries to the DB. How can we fix this?

![image](https://user-images.githubusercontent.com/63517174/113707162-2ad34500-96e8-11eb-8984-2f64770d3831.png)

This is how the DB looks like all the time. Only 1 entry

**Comment by singingwolfboy** [comment]
@MakufonSkifto It looks like you don't have a `user_id` for your table when you're storing OAuth tokens. Without a `user_id` column, you can't associate OAuth tokens with users. Please make sure you've read [the documentation for using the SQLAlchemy token storage](https://flask-dance.readthedocs.io/en/latest/storages.html#sqlalchemy-storage), as well as [the documentation for multi-user setups](https://flask-dance.readthedocs.io/en/latest/multi-user.html).

**Comment by MakufonSkifto** [comment]
@singingwolfboy Do i need to store the logged in users in a DB? It looks like I do and I really don't want to do that

**Comment by singingwolfboy** [comment]
@MakufonSkifto Yes, you do.

At this point, the topic of this issue has changed from "Discord OAuth isn't working" to "I need support with configuring Flask-Dance". I suggest that you review the documentation and the sample projects, such as the https://github.com/singingwolfboy/flask-dance-google-sqla project that I linked you to earlier. If you still have questions, please open a new issue.
