### ISSUE TITLE
Use flask_dance.contrib.google in a blueprint

### ISSUE THREAD

**Issue by Revisto** [singingwolfboy/flask-dance#343]
Hi, I need to use flask_dance OAuth in a blueprint but I believe that flask_dance's make_google_blueprint make its own blueprint and it's impossible to register that in a blueprint.
```
AttributeError: 'Blueprint' object has no attribute 'register_blueprint'
```

I would appreciate any help or solution.

**Comment by daenney** [comment]
```
 app.register_blueprint(
        make_google_blueprint(
            scope=['https://www.googleapis.com/auth/userinfo.profile',
                   'https://www.googleapis.com/auth/userinfo.email',
                   'https://www.googleapis.com/auth/cloud-platform']),
        url_prefix='/login')
```

**Comment by daenney** [comment]
You can't put blueprints in blueprints, they're registered on the app with a URL prefix. That's how Flask works.
