### ISSUE TITLE
oauthlib.oauth2.rfc6749.errors.TokenExpiredError

### ISSUE THREAD

**Issue by rmoorman** [singingwolfboy/flask-dance#35]
When using the google auth example setup code, an `oauthlib.oauth2.rfc6749.errors.TokenExpiredError` is being thrown in case the access token received is expired which causes an internal server error to be shown.

I suppose that exception should be handled by flask-dance itself by catching it and in case of a missing refresh token as seen here, trashing the auth info and probably initiating re-authentication.
I did not test however what happens with forced approval prompt and offline access type (as further described here http://googlecode.blogspot.nl/2011/10/upcoming-changes-to-oauth-20-endpoint.html and on various other places of course..) which forces refresh token passing upon authentication.
### How to reproduce

1) create new project with a fresh set of credentials using the developer console of google with correct redirect urls (http://localhost:5000/login/google/authorized for example)

2) add the credentials to the google auth example code
My example code so far (with added logging and an adjustment to let it work over plain HTTP for the sake of this example and dumping the whole user info instead of just the email) is:

``` .python
from flask import Flask, redirect, url_for
from flask_dance.contrib.google import make_google_blueprint, google

app = Flask(__name__)
app.secret_key = "supersekrit"
app.debug = True
import os
os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

blueprint = make_google_blueprint(
    client_id="my-key-here",
    client_secret="my-secret-here",
    scope=["profile", "email"]
)
app.register_blueprint(blueprint, url_prefix="/login")

# Some logging setup
import logging
stream_handler = logging.StreamHandler()
formatter = logging.Formatter(
    "[%(asctime)s] [%(process)d] [%(levelname)s] [%(name)s]: "
    "%(pathname)s:%(lineno)d - "
    "%(message)s"
)
stream_handler.setFormatter(formatter)
app.logger.addHandler(stream_handler)
app.logger.info("app started")
logging.basicConfig(level=logging.DEBUG)

@app.route("/")
def index():
    if not google.authorized:
        return redirect(url_for("google.login"))
    resp = google.get("https://www.googleapis.com/oauth2/v1/userinfo")
    assert resp.ok, resp.text
    return resp.text

if __name__ == "__main__":
    app.run()
```

3) start the app and authenticate once (maybe using an incognito browser session). Over here this causes the following output:

```
INFO:werkzeug:127.0.0.1 - - [27/Nov/2015 15:03:16] "GET / HTTP/1.1" 302 - 
DEBUG:requests_oauthlib.oauth2_session:Generated new state xxx. 
https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=xxx.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin%2Fgoogle%2Fauthorized&scope=profile+email&state=xxx 
INFO:werkzeug:127.0.0.1 - - [27/Nov/2015 15:03:16] "GET /login/google HTTP/1.1" 302 - 
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://accounts.google.com/o/oauth2/token using method POST. 
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'redirect_uri': 'http://localhost:5000/login/google/authorized', 'code': 'xxx', 'client_id': 'xxx.apps.googleusercontent.com', 'client_secret': 'xxx', 'grant_type': 'authorization_code'} 
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'timeout': None, 'verify': True, 'json': None, 'auth': None}. 
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com 
DEBUG:requests.packages.urllib3.connectionpool:"POST /o/oauth2/token HTTP/1.1" 200 None 
DEBUG:requests_oauthlib.oauth2_session:Prepared fetch token request body grant_type=authorization_code&code=xxx&client_id=xxx.apps.googleusercontent.com&client_secret=xxx&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin%2Fgoogle%2Fauthorized 
DEBUG:requests_oauthlib.oauth2_session:Request to fetch token completed with status 200. 
DEBUG:requests_oauthlib.oauth2_session:Request headers were {'Content-Length': '277', 'Accept': 'application/json', 'Connection': 'keep-alive', 'User-Agent': 'python-requests/2.8.1', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Accept-Encoding': 'gzip, deflate'} 
DEBUG:requests_oauthlib.oauth2_session:Request body was redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin%2Fgoogle%2Fauthorized&code=xxx&client_id=xxx.apps.googleusercontent.com&client_secret=xxx&grant_type=authorization_code 
DEBUG:requests_oauthlib.oauth2_session:Response headers were {'Expires': 'Fri, 01 Jan 1990 00:00:00 GMT', 'Alt-Svc':
'quic=":443"; ma=604800; v="30,29,28,27,26,25"', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Content-Disposition': 'attachment; filename="json.txt"; filename*=UTF-8\'\'json.txt', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 27 Nov 2015 14:04:37 GMT', 'Server': 'GSE', 'Pragma': 'no-cache', 'Content-Encoding': 'gzip', 'X-XSS-Protection': '1; mode=block', 'Alternate-Protocol': '443:quic,p=1', 'Set-Cookie': 'xxx', 'Cache-Control': 'no-cache, no-store, max-age=0,
must-revalidate', 'P3P': 'CP="This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info."', 'Content-Type': 'application/json; charset=utf-8'} and content { 
 "access_token" : "xxx", 
 "token_type" : "Bearer", 
 "expires_in" : 3600, 
 "id_token" : "xxx" 
}. 
DEBUG:requests_oauthlib.oauth2_session:Invoking 0 token response hooks. 
DEBUG:requests_oauthlib.oauth2_session:Obtained token {'access_token': 'xxx', 'id_token': 'xxx', 'expires_at': 1448636677.8191292, 'expires_in': 3600, 'token_type': 'Bearer'}. 
INFO:werkzeug:127.0.0.1 - - [27/Nov/2015 15:04:37] "GET /login/google/authorized?state=xxx&code=xxx HTTP/1.1" 302 - 
DEBUG:requests_oauthlib.oauth2_session:Invoking 0 protected resource request hooks. 
DEBUG:requests_oauthlib.oauth2_session:Adding token {'id_token': 'xxx', 'expires_in': 3600, 'expires_at': 1448636677.8191292, 'access_token': 'xxx', 'token_type': 'Bearer'} to request. 
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://www.googleapis.com/oauth2/v1/userinfo using method GET. 
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Authorization': 'Bearer xxx'} and data None 
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'allow_redirects': True}. 
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com 
DEBUG:requests.packages.urllib3.connectionpool:"GET /oauth2/v1/userinfo HTTP/1.1" 200 None 
INFO:werkzeug:127.0.0.1 - - [27/Nov/2015 15:04:38] "GET / HTTP/1.1" 200 -
```

4) forget about it for more than an hour (expires in 3600 seconds in my case)

5) refresh the page and see the exception `oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)`

**Comment by singingwolfboy** [comment]
Hey @rmoorman, thanks for the detailed debugging info! The `make_google_blueprint()` function accepts an `offline=True` argument, which will get an offline access token instead of a short-lived access token and a long-lived refresh token. As a workaround, you should be able to use this `offline=True` argument to get your code to work.

However, you're right that Flask-Dance should support online access tokens, especially since that is the default. Is there any chance that you could submit a pull request to make this improvement? I'd be happy to pair-code with you on this through Google Hangouts or Skype, if you'd like. I'm asking you this for two reasons: one, because I want more contributors on this project, rather than me writing all the code; and two, because I don't really know how to build this, and two brains are better than one. :)

**Comment by rmoorman** [comment]
Hello @singingwolfboy, I am glad if I can be of any help and good that you found the information useful.
What I am wondering is, thinking of a possible solution to the problem, what other cases would have to lead to a redirect to the login route.

Maybe something along the lines of this?
~~~~.python
from oauthlib.oauth2.rfc6749.errors import InvalidGrantError, TokenExpiredError, OAuth2Error

class OAuth2Session(BaseOAuth2Session):
    # ....
    def request(self, *args, **kwargs):
        try:
            return super(CustomOAuth2Session, self).request(*args, **kwargs)
            # ... and other logic of course already in place here
        except (InvalidGrantError, TokenExpiredError) as e: # or maybe any OAuth2Error
            raise AuthenticationError from e
~~~~
That logic would go into the already existing OAuth2Session class available and could intercept this and other errors and wrap them within a flask-dance specific exception type. Then, we could add some logic within the blueprint endpoints to catch those errors. But that still leaves us with those errors in views outside the blueprint.
Maybe the AuthenticationError could be a custom HTTPException with a redirect response? The session which throws the error knows about the blueprint so we could build a suitable redirect response, give it to the custom implementation of HTTPException and raise it from within the CustomOAuth2Session.

Do you think that this would be feasible and a good way to handle the issue within flask-dance?

https://github.com/singingwolfboy/flask-dance/blob/master/flask_dance/consumer/requests.py#L86
https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L267
https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/errors.py#L84
http://werkzeug.pocoo.org/docs/0.11/exceptions/#werkzeug.exceptions.HTTPException

**Comment by singingwolfboy** [comment]
Does this pull request provide the improvement you're looking for? https://github.com/singingwolfboy/flask-dance/pull/62

**Comment by renefs87** [comment]
I am experiencing exactly the same problem as @rmoorman with the Google Quickstart code, so it seems it is not fixed @singingwolfboy

**Comment by singingwolfboy** [comment]
While I don't actually know if this issue is fixed or not, I haven't been able to get enough information to be able to reproduce it in any way. As a result, I'm going to close this issue. If someone else comes across the same problem, please open a _new_ issue and link to this one, and be sure to include as much debugging information as possible. I can't fix the problem if I can't reproduce it!

**Comment by askhabaliev** [comment]
So

**Comment by rushiagr** [comment]
In a hurry at the moment, so not creating new ticket and adding info here:

Traceback:

```
Traceback (most recent call last):
  File "/home/ubuntu/.sandesh/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.sandesh/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.sandesh/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.sandesh/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/sandesh/dataapp.py", line 319, in index
    resp = google.get("/oauth2/v1/userinfo")
  File "/home/ubuntu/.sandesh/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/.sandesh/lib/python3.9/site-packages/flask_dance/consumer/requests.py", line 192, in request
    return super().request(
  File "/home/ubuntu/.sandesh/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request
    url, headers, data = self._client.add_token(
  File "/home/ubuntu/.sandesh/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)
```


Code: 

```python
    curr_app.config["GOOGLE_OAUTH_CLIENT_ID"] = secrets.GOOGLE_CLIENT_ID
    curr_app.config["GOOGLE_OAUTH_CLIENT_SECRET"] = secrets.GOOGLE_CLIENT_SECRET
    # curr_app.config["OAUTHLIB_RELAX_TOKEN_SCOPE"] = True
    # google_bp = make_google_blueprint(scope=["profile", "email"])
    google_bp = make_google_blueprint(
        scope=[
            "openid",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile",
        ]
    )

    @curr_app.route("/")
    def index():

        if not google.authorized:
            return redirect(url_for("google.login"))
        resp = google.get("/oauth2/v1/userinfo")
        print(resp.ok, resp.text)
        assert resp.ok, resp.text
        print("You are {email} on Google".format(email=resp.json()["email"]))

```

Steps to reproduce (at least that's how it got reproduced by me accidentally once. Haven't tried it again yet):
1. Go to the index page and login user to the page via the auth workflow
2. Wait for a few hours (~10 hours for me)
3. Go to the same index page again

**Comment by gg4u** [comment]
Also met this issue.

Steps to reproduce:

1. load the /user endpoint 
2. succesffully login
3. wait for less than 2/3 hours, reload the page, and the token is gone
4. reload the /user endpoint result in broken server
5. Cleaning the cookies won't help (broken serveR)


```
@app.route("/user")
def user():
	if not google.authorized:
		return redirect(url_for("google.login"))
	resp = google.get("/oauth2/v1/userinfo")
	assert resp.ok, resp.text
	print("You are {email} on Google".format(email=resp.json()["email"]))
	user = {'email' : resp.json()}
	return render_template('user.html' , **user)
```

```

Traceback (most recent call last):
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/venv/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/venv/lib/python3.7/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/app.py", line 41, in user
    resp = google.get("/oauth2/v1/userinfo")
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/venv/lib/python3.7/site-packages/flask_dance/consumer/requests.py", line 199, in request
    **kwargs,
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 484, in request
    url, http_method=method, body=data, headers=headers
  File "/Users/gg4u/Sites/IIT/innovationFlowApp/venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()

```

**Comment by s-AlirezaSadeghi** [comment]
> I am experiencing exactly the same problem as @rmoorman with the Google Quickstart code, so it seems it is not fixed @singingwolfboy
> 
> This is how I made It work the simplest way:
> 
> ```python
>     if not google.authorized:
>         return redirect(url_for("google.login"))
>     try:
>         resp = google.get("/plus/v1/people/me")
>         assert resp.ok, resp.text
>     except (InvalidGrantError, TokenExpiredError) as e:  # or maybe any OAuth2Error
>         return redirect(url_for("google.login"))
> ```
> 
> Edit: Add Simple and ugly fix to application.

How would you deal with this when writing tests using Pytest. Monkeypatching will deal with authorized condition (https://flask-dance.readthedocs.io/en/v1.1.0/testing.html) but not necessarily the Try block. It will fail as  it does not have valid token for get request during testing. Any suggestion on that ?

**Comment by holdenweb** [comment]
This issue just cost me over a week's spare-time head scratching. I believe I have a fix for it which doesn't involve any changes to flask-dance.

My experience was that whether or not I use `offline=True` I don't reliably get a refresh token. Reasoning that flask-dance can obtain an access token the very first time a user uses it, it must be possible to obtain a _new_ token in the same way. I therefore added a `before_request` function that deletes the `google_oauth_token` key from the Flask session if it detects that it's expired:

    @app.before_request
    def before_request():
        if (token := (s := flask.session).get('google_oauth_token')):
            print("Token expiring in", token['expires_at']-time.time())
            if time.time() >= token['expires_at']:
                del s['google_oauth_token']
    
This has so far appeared to work well, though I have not yet tested it with an expired token on a POST request and suspect that might cause difficulties. Perhaps someone closer to the flask-dance code can check it out, and perhaps write some rigorous test cases around this technique?

**Comment by ban3a1** [comment]
On a local host, 
`export OAUTHLIB_INSECURE_TRANSPORT=1`
worked for me
