### ISSUE TITLE
Make new release without sqlalchemy-utils?

### ISSUE THREAD

**Issue by kvalv** [singingwolfboy/flask-dance#354]
dependency on `sqlalchemy-utils` makes it impossible for us to use `sqlalchemy 1.4.0`. So I'm glad to see #350 removing this dependency. Is it possible to create a release containing this commit anytime soon?

**Comment by daenney** [comment]
That was discussed in #349. We're waiting a few days to land some other changes.

**Comment by singingwolfboy** [comment]
Flask-Dance 4.0.0 is now released! https://pypi.org/project/Flask-Dance/4.0.0/
