### ISSUE TITLE
Google Group authentication

### ISSUE THREAD

**Issue by chrisroat** [singingwolfboy/flask-dance#366]
Is it possible to have authentication based on membership in a Google Group?

**Comment by singingwolfboy** [comment]
Once the user has gone through the Google OAuth flow, it should be possible to use the Google APIs to check which groups the user is a member of. Then you can take action based on that, to allow or deny the user based on whatever criteria you want.

So yes, what you're looking for is entirely possible. However, Flask-Dance will only help you with getting the user through the OAuth flow. Everything else, including checking group membership, is up to you and your application code to implement.

Does that answer your question?

**Comment by chrisroat** [comment]
Yes, thanks for the fast response.   I understand better the scope of the project.

I am trying a check on before every request, so this would mean doing the extra call each time.  Below is my check for github user name, which I am thinking of switching over to the Google Group check.  Is there a standard way to avoid always doing both these lookups for every request (get for the username, and now the group lookup)?  

```
    @pipeline_bp.before_request
    def check_valid_login():
        if not github.authorized:
            session["next_url"] = request.url
            return redirect(url_for("github.login"))
        resp = github.get("/user")
        if not resp.ok:
            abort(401)
        data = resp.json()
        if data["login"] not in allowed_github_users:
            abort(403)

    github_bp = make_github_blueprint(
        client_id=os.environ["FRONTEND_CLIENT_ID"],
        client_secret=os.environ["FRONTEND_CLIENT_SECRET"],
    )
    app.register_blueprint(github_bp, url_prefix="/login")
```

**Comment by singingwolfboy** [comment]
I suggest using a dedicated authentication/authorization framework, like Flask-Login. [The Flask-Dance quickstart for Google with SQLAlchemy](https://github.com/singingwolfboy/flask-dance-google-sqla) provides a good example of how to do this.

**Comment by chrisroat** [comment]
Thanks for the advice.  Adding user accounts and a database seems heavyweight, but perhaps this is the way.  I might also explore storing something in the session.

**Comment by daenney** [comment]
Group memberships do change, but they don't tend to be super dynamic. You could chose to store this in a cache, and refresh that information from time to time. An LRU cache with TTL (say 10min) containing group memberships keyed on the user ID.

A concrete example could be subclassing [cachetools.TTLCache](https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache) and implement `def __missing__(self, key)` on it, so it'll fetch the group information only when it's accessed and isn't cached.

**Comment by chrisroat** [comment]
Thanks for the explanations and advice.
