### ISSUE TITLE
How to migrate existing users to Firebase?

### ISSUE THREAD

**Issue by samanyougarg** [singingwolfboy/flask-dance#367]
Hi @singingwolfboy,

Thank you very much for creating this awesome library. We have been using it for the last year or so and it has helped us a lot.

We are working on v2 of our application where we are migrating from Flask to FastAPI and are using Firebase to manage our authentication.

Can you please guide me on how we can migrate the existing users from Flask Dance Oauth (we only use Google login) to Firebase?

Your help will be much appreciated!

**Comment by daenney** [comment]
> We are working on v2 of our application where we are migrating from Flask to FastAPI and are using Firebase to manage our authentication.

Flask-Dance is a Flask plugin. We can help out with issues related to integrating oauth into your Flask app, but we're not really versed or well suited to tell you how to refactor your app and migrate user data to a different framework.

If all you're doing is using oauth2 and you don't ever store things like access/refresh tokens except for in cookies, then there's really nothing for you to do aside from integrating oauth into your new app.

If you are storing artifacts of the oauth dance in something like a database, you'll need to migrate that yourself to whatever the format is that a FastAPI oauth plugin expects. There's a tutorial up on the FastAPI website on how to integrate oauth in it: https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/.
