### ISSUE TITLE
invalidate_cached_property will be abandoned in Werkzeug 2.1

### ISSUE THREAD

**Issue by HelloRusk** [singingwolfboy/flask-dance#369]
This module sometimes yields warnings around `invalidate_cached_property` function.

```
  /*/versions/3.8.0/lib/python3.8/site-packages/flask_dance/consumer/requests.py:122: DeprecationWarning: 'invalidate_cached_property' is deprecated and will be removed in Werkzeug 2.1. Use 'del obj.name' instead.
    invalidate_cached_property(self, "token")
```

https://github.com/pallets/werkzeug/blob/main/src/werkzeug/utils.py#L131-L136

Seems that we should just use `delattr(obj, name)` for deleting properties

**Comment by davidism** [comment]
Note that Flask-Dance will start failing with Werkzeug 2.1 until this is addressed. I will probably release 2.1 before 2022.

**Comment by davidism** [comment]
Well, it might not _fail_, because you still have compat code for it, but you should really migrate to `del obj.attr` instead.

**Comment by HelloRusk** [comment]
close since #382 solved the problem
