### ISSUE TITLE
flask-dance 6.0.0 incompatable with Flask >=2.2.0

### ISSUE THREAD

**Issue by rez10191** [singingwolfboy/flask-dance#396]
Hello,

Flask 2.2.0 was released today.  This release included this change list: https://github.com/pallets/flask/commit/0b2f809f9b56861dae3ae5154d73b4afaf632a0a which removes the `_lookup_app_object` function that is imported from `flask_dance/contrib/google.py`, as well as many other `contrib` modules by the looks of it.  The function was properly marked as a private.

Thanks for your great work on this project!

Richard Zuber

**Comment by BlitzJB** [comment]
Faced the same issue! @rez10191 Can you point me in the general direction of a workaround? I could put some time into this and submit a PR!

**Comment by singingwolfboy** [comment]
I just released Flask-Dance 6.1.0, which switches to using `flask.g` for storing information, as recommended by the Flask release notes. Thanks for the heads-up about this change!
