### ISSUE TITLE
QuickStart/documentation doesn't say what "github.get('/user')" DOES

### ISSUE THREAD

**Issue by maxrothman** [singingwolfboy/flask-dance#4]
The QuickStart shows calling `github.get('/user')`, but it doesn't say what that line is intended to *do* (get the user resource). It might also be good for the example to include de-json-ifying the response body and get something useful from it, e.g. display the user's username.

**Comment by singingwolfboy** [comment]
I've improved and reorganized the docs in version 0.5.0. I'm closing this issue -- please reopen it (or open a new one) if the docs are still confusing.
