### ISSUE TITLE
OAuth 2 MUST utilize https. How can I make the redirect_uri be https?

### ISSUE THREAD

**Issue by db0** [singingwolfboy/flask-dance#402]
Sorry if this is something obvious but I've been struggling with this for the past day and I can't figure it out.

I've set up this implementation https://github.com/db0/KoboldAI-Horde/blob/master/server.py#L471 for discord oauth

Whenever I turn off `os.environ['OAUTHLIB_INSECURE_TRANSPORT']` my authentication fails due to the dance not happening through https. However no matter what I do, I can't see a way to make the `redirect_uri` in the initial request be in https

So when I [url_for('discord.login')](https://github.com/db0/KoboldAI-Horde/blob/master/server.py#L434) I am redirected to 

```
https://discord.com/oauth2/authorize?response_type=code&client_id=1016808045433315260&redirect_uri=http%3A%2F%2Fkoboldai.net%2Fdiscord%2Fdiscord%2Fauthorized&scope=identify&state=6MpeICOZdbY8WVO222Z536w5FG7bYI&prompt=consent
```

so the `redirect_uri` in that url is always `http://`. 

How can I set my code so that it uses https?

**Comment by singingwolfboy** [comment]
Have you read this? https://flask-dance.readthedocs.io/en/latest/proxies.html

**Comment by db0** [comment]
No, I couldn't find the right search terms to land to that >_< Thanks reading it now

**Comment by db0** [comment]
I added the X-Forwarded-Proto to "https" with no luck. Found this thread as well https://github.com/singingwolfboy/flask-dance/issues/188 but I am still failing. Still looking but any help would be appreciated. This is my current apache config which is just what the letsencrypt set up for me plus the new header

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerAdmin mail@dbzer0.com
        ServerName koboldai.net

        ProxyPreserveHost On
        ProxyRequests Off
        ProxyPass / http://localhost:5001/
        ProxyPassReverse / http://localhost:5001/


RequestHeader set "X-Forwarded-Proto" "https"
SSLCertificateFile /etc/.../fullchain.pem
SSLCertificateKeyFile /etc/.../privkey.pem
Include /etc/.../foo.conf
</VirtualHost>
</IfModule>
```

**Comment by singingwolfboy** [comment]
You're proxying to port 5001? Are you trying to use the Flask dev server for deployment? If so, that's a really bad idea for all sorts of reasons. Have you checked the docs here? https://flask.palletsprojects.com/en/2.2.x/deploying/

**Comment by db0** [comment]
Actually I'm using waitress. And on the same note, I also just found an easy workaround:

```
serve(REST_API, host="0.0.0.0", port="5001",url_scheme='https')
```

This actually makes flask send the `redirect_uri` as https which finally solves this issue!

Hopefully this will help someone else in the future
