### ISSUE TITLE
Anaconda support

### ISSUE THREAD

**Issue by Sclafus** [singingwolfboy/flask-dance#417]
Hello there! Thanks for this nice piece of software.
I have a quick question: are you supporting Anaconda? I see that [there is a package on conda-forge](https://anaconda.org/conda-forge/flask-dance), but it has not been updated since v2.2.0
Should I assume that this is a rebundle by some random user and you are not supporting it directly?

**Comment by singingwolfboy** [comment]
Correct, I am not supporting Anaconda. I have no problem with other people putting Flask-Dance on Anaconda, but I did not do so, and I cannot provide support for whatever package version may be on Anaconda.

**Comment by Sclafus** [comment]
Thanks for the answer, I will close the issue since there is nothing more to add
