### ISSUE TITLE
Flask-Dance[sqla] not in pypi?

### ISSUE THREAD

**Issue by mmilkin** [singingwolfboy/flask-dance#46]
```
pip install Flask-Dance[sqla]
...
no matches found: Flask-Dance[sqla]
```

Was the sql version removed from pypi?

**Comment by singingwolfboy** [comment]
@mmilkin: no, it's still there. Are you using ZSH for your shell? You may need to put quotes around the package name, so that ZSH doesn't try to parse the brackets. For example:
```zsh
pip install "Flask-Dance[sqla]"
```

**Comment by mmilkin** [comment]
argh silly zsh :)
