### ISSUE TITLE
Google and probably other non-spec compliant providers broken

### ISSUE THREAD

**Issue by silas** [singingwolfboy/flask-dance#47]
This isn't something you can fix, but I figured I'd open an issue so other developers can avoid a maddening debug session.

requests-oauthlib started sending basic auth headers in 6.0.0, which is spec compliant but breaks a lot of existing providers (including Google).

The current work around is to lock requests-oauthlib to the previous version: `requests-oauthlib==0.5.0`

See requests/requests-oauthlib#218 (Google) and requests/requests-oauthlib#221 (LinkedIn)

Hopefully this can be closed after their next release.

**Comment by singingwolfboy** [comment]
Thanks for the heads-up, @silas. I'll pay attention to requests-oauthlib's release schedule, and when the next release comes out, I'll do some testing with Flask-Dance.

The good news is, it looks like this change means that we can support Bitbucket with Flask-Dance! :dancer:

**Comment by singingwolfboy** [comment]
Looks like this is fixed (or at least fixable) as of [requests-oauthlib 0.6.2](https://github.com/requests/requests-oauthlib/commit/ed091d296b01550ce8e63bf5663b766a3587083d). I'll test it out in the next few days.

**Comment by singingwolfboy** [comment]
I did some testing, and it seems to me like Google is working with the latest release. I also tested Bitbucket, and found that I could almost make it work -- need some improvements in #62, which is waiting on https://github.com/requests/requests-oauthlib/pull/251 to be merged.

@silas, can you let me know if you can reproduce that failure with Flask-Dance and Google?

**Comment by silas** [comment]
@singingwolfboy If it's working for you I think we can just close the issue (I'm not going to have time to test it properly anytime soon). Thanks for following up and maintaining the project, much appreciated!
