### ISSUE TITLE
How to request offline access to Google

### ISSUE THREAD

**Issue by leto** [singingwolfboy/flask-dance#5]
I am looking to request offline access so I can use a refresh token with the Google OAuth2 API. Otherwise, the tokens that Flask-Dance gets are only valid for 1 hour. Can you give an example or describe how I would use Flask-Dance to do this?

https://developers.google.com/accounts/docs/OAuth2WebServer#offline

https://developers.google.com/accounts/docs/OAuth2WebServer#refresh

**Comment by leto** [comment]
Any ideas about this, @singingwolfboy ?

**Comment by singingwolfboy** [comment]
Hey @leto, I just committed a change that should allow you to request an offline token: https://github.com/singingwolfboy/flask-dance/commit/9bcfedcfd9662e4bb24152887546e85376eba322 Could you please try running that code and make sure that it works correctly? I wrote an automated test to cover this change, but I haven't tested it against the real Google APIs at all.

**Comment by leto** [comment]
Awesome! Will do that very shortly. Also, I found this: http://requests-oauthlib.readthedocs.org/en/latest/examples/real_world_example_with_refresh.html and I am currently trying to figure out how to do that with Flask-Dance

**Comment by singingwolfboy** [comment]
Let me know what you figure out, @leto! Flask-Dance is built on top of requests-oauthlib, so you should be able to make Flask-Dance do anything that requests-oauthlib can do. If you find that you need to change the code to make it do what you want, then please send a pull request! Just keep in mind that your changes will need to have automated tests and documentation, to maintain high code quality. :)

**Comment by leto** [comment]
Not sure this is working correctly. I don't see the offline param getting sent to the Google APIs. Have you tried it locally?

**Comment by singingwolfboy** [comment]
@leto, no I mentioned that: "I haven't tested it against the real Google APIs at all". Can you give me a concrete test case?

**Comment by singingwolfboy** [comment]
I haven't heard back from you, so I'm closing this issue.

**Comment by leto** [comment]
I am just now circling back to this, I will report back if I have more data.
