### ISSUE TITLE
Change GitHub scope based on user?

### ISSUE THREAD

**Issue by embik** [singingwolfboy/flask-dance#51]
This is more a question than an issue but I did not find a more suited place to ask and did not want to bother @singingwolfboy via private E-Mail, so here we go:

I'm writing a Flask web app that utilizes flask-dance for GitHub authentication. 99,99% of all users will only need minimal information from GitHub and the default scope is defined that way: Minimal. But a few selected users will act as administrators and import additional information from GitHub (organization, repositories, quite a lot of information). Is it possible to use a different scope based on the user that is signing in (identified by the GitHub username)? I was thinking I might need to do the OAuth dance twice (first for identifying the user and to fetch their username), but I'm not sure this is a sane approach.

And thank you very much for creating this awesome flask extension - It's a lifesaver!

**Comment by singingwolfboy** [comment]
Hmm, good question. Right now, the scope information is baked into the blueprint itself, and can't be modified on a per-user basis. I suppose you could create two blueprints, one for the minimal scope and one for the admin scope, and then redirect the user to the correct blueprint view as necessary. For example:

```python
github_bp = OAuth2ConsumerBlueprint("github", __name__,
    client_id="my-client-id",
    client_secret="my-client-secret",
    scope=None,
    base_url="https://api.github.com/",
    authorization_url="https://github.com/login/oauth/authorize",
    token_url="https://github.com/login/oauth/access_token",
)
github_admin_bp = OAuth2ConsumerBlueprint("github-admin", __name__,
    client_id="my-client-id",
    client_secret="my-client-secret",
    scope=["repo", "admin:repo_hook", "admin:org_hook"],
    base_url="https://api.github.com/",
    authorization_url="https://github.com/login/oauth/authorize",
    token_url="https://github.com/login/oauth/access_token",
)

app = Flask(__name__)
app.secret_key = "anything-you-want"
app.register_blueprint(github_bp, url_prefix="/login")
app.register_blueprint(github_admin_bp, url_prefix="/login")

@app.route("/")
def index():
    # this is non-functioning pseudo-code
    if user.act_as_administrator():
        redirect(url_for("github-admin.login"))
    else:
        redirect(url_for("github.login"))
```

However, that's not a very good solution, since it involves a fair amount of code duplication. Maybe the `scope` parameter could accept a dictionary mapping a name to a list of scopes, and when you redirect to the `login` view, you could optionally include a URL parameter that indicates which name you want to use? How would you feel about that?

**Comment by embik** [comment]
To me it does sound worth developing it, however I'd understand displeasure for developing something just because one user asked for it (I didn't take a look at the code internals yet so I have no idea how much work needs being done here). The kinda crux-y thing in your proposed solution seems to be that the app has to know the username _before_ redirecting, if I understand correctly.

**Comment by singingwolfboy** [comment]
Since no one has made any progress on this issue in more than a year, I'm going to close it. If someone else wants to tackle this work, we can open a new issue that references this one.

**Comment by temurchichua** [comment]
I know it's way too late for a response but there is something i did.

I had a same issue for facebook and in Flask_Dance files I added default value for a "name" variable: >>> `contrib.facebook.py`
``` python
def make_facebook_blueprint(
    name = "facebook",
    client_id=None,
    ....
    storage=None,
):
    facebook_bp = OAuth2ConsumerBlueprint(
        name,
        __name__,
        client_id=client_id,
        ...
        storage=storage,
    )

```
Thus i was able to simply create two different blueprints for different purposes:
 ``` python
page_blueprint = make_facebook_blueprint(
    name='fb_page_access',
    storage=SQLAlchemyStorage(PageAccessModel, db.session, user_id=current_user),
    scope=['manage_pages']
)
```

``` python
fb_blueprint = make_facebook_blueprint(
    storage=SQLAlchemyStorage(OAuth, db.session, user=current_user),
    scope=['email']
)
```
It might not be the best approach but it helped me to use the existing oauth templates.
