### ISSUE TITLE
Get Webhook info for Slack

### ISSUE THREAD

**Issue by Jonovono** [singingwolfboy/flask-dance#63]
Hi. As per slacks documention I should get some slack webhook info on auth. Like:

```
{
"access_token": "xoxp-XXXXXXXX-XXXXXXXX-XXXXX",
"scope": "incoming-webhook,commands,bot",
"team_name": "Team Installing Your Hook",
"team_id": "XXXXXXXXXX",
"incoming_webhook": {
    "url": "https://hooks.slack.com/TXXXXX/BXXXXX/XXXXXXXXXX",
    "channel": "#channel-it-will-post-to",
    "configuration_url": "https://teamname.slack.com/services/BXXXXX"
},
"bot":{
    "bot_user_id":"UTTTTTTTTTTR",
    "bot_access_token":"xoxb-XXXXXXXXXXXX-TTTTTTTTTTTTTT"
    }
}
```

However, I don't see the 'incoming_webhook' information. I see the bot key and everything else. Any idea why? 

Thanks.

**Comment by singingwolfboy** [comment]
No idea. It could be that Slack's documentation is incorrect. Can you provide a reproducible test-case? If I can reproduce the problem, I might be able to give you some better information.
