### ISSUE TITLE
Issues with examples

### ISSUE THREAD

**Issue by 4c74356b41** [singingwolfboy/flask-dance#66]
Hello, so I've installed this wonderful extension, and got it to work, with a bit of a hack (more on this later). What I found - the examples in the documentation are a bit of.

    @app.route("/")
    def index():
        if not azure.authorized:
            return redirect(url_for("azure.login"))
        resp = azure.get("/v1.0/me")
        assert resp.ok
        return "You are {mail} on Azure AD".format(mail=resp.json()["mail"])

So this code doesnt reach code after `resp = azure.get("/v1.0/me")`? Is this expected? If it is, why this code is even there? But this code runs if you go to the same page again.

So I have 2 questions:
1. How to setup session variable with the username? (I've done this with a super hack)
2. Why do you have `assert resp.ok` in the code if it doesn't get reached?

As for my hack, I'm redirecting back to login page after successful auth, to update session with a property containing username. that's pretty hackish, what's the proper way to do that?
Thanks!

**Comment by singingwolfboy** [comment]
I'm confused by your question. Why do you say that the code doesn't execute the lines after fetching from the Azure API? And what do you mean by setting up a session variable with the username?

If you want to run code immediately after a successful OAuth interaction, use the `oauth_authorized` signal, documented here: http://flask-dance.readthedocs.io/en/latest/signals.html
