### ISSUE TITLE
Facebook.authorized is True even though the user clicked "Cancel"

### ISSUE THREAD

**Issue by nickslavsky** [singingwolfboy/flask-dance#68]
Hi! I'm writing a small prototype and came across a weird behavior.
I have these 2 pieces of code:
```python
blueprint = make_facebook_blueprint(
    client_id="...",
    client_secret="...",
    scope=['email'],
    redirect_url="/oauth2callback"
)

@app.route('/oauth2callback')
def oauth2callback():
    if facebook.authorized:
        me = facebook.get('me?fields=id,first_name,email').json()
        social_id, username, email = me['id'], me['first_name'], me['email']
        user = User.query.filter_by(social_id=social_id).first()
        if not user:
            user = User(social_id=social_id, nickname=username, email=email)
            db.session.add(user)
            db.session.commit()
        login_user(user, True)
    return redirect(url_for('index'))
```

And if the user clicks Cancel during the authorization dance the 'facebook.authorized' returns 'True'.

What am I doing wrong here? Thanks in advance!

**Comment by singingwolfboy** [comment]
Neither you nor I can control how Facebook chooses to implement OAuth, and it may choose to give you an OAuth token that has no permissions if the user clicks "cancel" during the authorization step. You can check for this by using the `oauth_authorized` signal, as documented here: http://flask-dance.readthedocs.io/en/latest/signals.html

**Comment by nickslavsky** [comment]
Thanks for the tip! You're right, I have switched to actually checking the contents of the response instead of `Facebook.authorized` field. I guess we can close the issue now.
