### ISSUE TITLE
No documentation on allowed redirect URIs

### ISSUE THREAD

**Issue by maxrothman** [singingwolfboy/flask-dance#7]
Some OAuth providers (Google, for example) require you to set explicit allowed redirect URIs. It is non-obvious from existing documentation what URI flask-dance requires be set there. It should be set to `http://:hostname/:flask-dance-url-prefix/:provider/authorized`, e.g. for Google OAuth `http://localhost:5000/login/google/authorized`

**Comment by leto** [comment]
:+1: to improving the docs for this. They were confusing to me as well

**Comment by singingwolfboy** [comment]
@leto and @maxrothman, this point has nothing to do with Flask-Dance, and everything to do with the OAuth protocol itself. However, [I've written some documentation about OAuth](http://flask-dance.readthedocs.org/en/latest/how-oauth-works.html) to try to clarify the situation, and I [added a quickstart specifically for Google](http://flask-dance.readthedocs.org/en/latest/quickstarts/google.html) as well. Do those help? What else can I do to make it clearer?

**Comment by leto** [comment]
The quickstarts are very helpful, if I had read those when starting out I would have been less confused. Perhaps just pointing people to the quickstarts from more parts of the docs?

**Comment by singingwolfboy** [comment]
I've improved and reorganized the docs in version 0.5.0. I'm closing this issue -- please reopen it (or open a new one) if the docs are still confusing.
