### ISSUE TITLE
Does this work with rest-plus?

### ISSUE THREAD

**Issue by seekheart** [singingwolfboy/flask-dance#95]
Wanted to ask if there are any examples or if flask-dance can work with flask-rest-plus?
I'm currently looking for an Oauth lib that can with google for a restful backend I have in the works.

**Comment by singingwolfboy** [comment]
@seekheart I'm not sure exactly what you're asking. You can use whatever libraries you want in your Python project. I don't think that Flask-Dance _integrates_ with the library you mentioned, but it shouldn't be affected by it either.

I would recommend that you give it a try. If you run into a problem, then please create a more specific GitHub Issue and let me know!

**Comment by seekheart** [comment]
alright, much appreciated @singingwolfboy
